BEGIN TRANSACTION;
CREATE TABLE dependencies (
    id          INTEGER PRIMARY KEY,
    project     TEXT NOT NULL,
    name        TEXT NOT NULL,
    location    TEXT,
    source_url  TEXT,
    why         TEXT NOT NULL,
    critical    INTEGER NOT NULL DEFAULT 1,
    UNIQUE (project, name),
    FOREIGN KEY (project) REFERENCES projects(name) ON DELETE CASCADE
);
INSERT INTO "dependencies" VALUES(1,'dr-companion','Ruby4Lich5','C:/Ruby4Lich5','https://github.com/elanthia-online/lich-5/releases','Lich runs on Ruby; dr-companion automates Lich. Captured in no manifest.',1);
INSERT INTO "dependencies" VALUES(2,'dr-companion','Genie4','C:/Genie4',NULL,'Simutronics client dr-companion works alongside.',1);
INSERT INTO "dependencies" VALUES(3,'quickgrade','playwright + chromium browser cache','Downloads/testgrader/tools/node_modules and AppData/Local/ms-playwright','https://playwright.dev','The whole 21-suite harness is Playwright driving headless Chromium. tools/package.json names playwright, but nothing records that the browser binaries live in a separate machine-wide cache that can be stripped independently of node_modules. Both have to be present: npm install, then npx playwright install chromium.',1);
INSERT INTO "dependencies" VALUES(4,'quickgrade','CPython 3.13','AppData/Local/Programs/Python/Python313/python.exe',NULL,'build.py regenerates sw.js and the single-file QuickGrade.html, and the build test fails without it. No manifest names an interpreter, and the obvious names on PATH are Store aliases that do nothing. See trap python-none-on-path.',1);
INSERT INTO "dependencies" VALUES(5,'dr-companion','ComfyUI','http://127.0.0.1:8188','https://github.com/comfyanonymous/ComfyUI','The whole art pipeline talks to it over HTTP. tools/art-daemon.mjs waits for it rather than exiting, so a missing ComfyUI looks like a daemon that is running and producing nothing. Needs the ImageScale and SaveImage nodes, which the daemon uses to emit a thumbnail it scores itself on.',1);
INSERT INTO "dependencies" VALUES(6,'dr-companion','FLUX.1-schnell fp8 checkpoint','flux1-schnell-fp8.safetensors','https://huggingface.co/black-forest-labs/FLUX.1-schnell','schnell is Apache 2.0 and puts no conditions on its output, so the art pack can be shipped commercially and given to Simutronics. FLUX.1-dev is also on this machine and is NON-COMMERCIAL: swapping it in would make the entire pack legally unusable. Pinned in art-daemon.mjs and art-run.mjs and must never be changed.',1);
INSERT INTO "dependencies" VALUES(7,'dr-companion','Genie 4 map XML','C:\Genie4\Maps','https://www.playdragonrealms.com/','85 XML files, the community cartography the whole map is built from. tools/build-map.mjs reads them into src/data/map. The built JSON is committed, so a build is only needed when the maps change, but without these the map cannot be regenerated at all.',1);
INSERT INTO "dependencies" VALUES(8,'dr-companion','Node 24 or newer','C:\Program Files\nodejs','https://nodejs.org/','The test suite imports TypeScript directly (tools/trail-test.mjs and tools/flow-test.mjs import from src/lib/*.ts) and relies on native type stripping. On an older Node those suites do not run.',1);
INSERT INTO "dependencies" VALUES(9,'dr-companion','Python 3.13','C:\Users\Admin\AppData\Local\Programs\Python\Python313','https://www.python.org/','Not used by the app. Recorded because `python` on PATH resolves to the Microsoft Store stub and fails with Permission denied, which reads as "Python is missing" when it is installed. Use the full path.',0);
INSERT INTO "dependencies" VALUES(10,'world-aflame-godot','Public STUN server (stun.l.google.com:19302)','hardcoded in scripts/net/net_manager.gd, ICE_SERVERS const',NULL,'NAT traversal for serverless P2P WebRTC play -- no manifest records this since it''s an external network dependency, not a package. No fallback if Google''s STUN server ever goes away or blocks this traffic.',1);
INSERT INTO "dependencies" VALUES(11,'world-aflame-godot','Godot 4.7.2 Standard (non-Mono) build','C:\Users\Admin\AppData\Local\Programs\Godot\Standard',NULL,'Mono build has zero Web export templates -- this project is pure GDScript specifically so it can use the Standard build and export to Web. Separate install from the Mono build at ...\Godot\Godot_v4.7.2-stable_mono_win64, which is not used by this project.',1);
CREATE TABLE events (
    id          INTEGER PRIMARY KEY,
    ts          TEXT NOT NULL DEFAULT (datetime('now')),
    session     TEXT,
    kind        TEXT NOT NULL CHECK (kind IN
                  ('decision','error','milestone','removal','install')),
    summary     TEXT NOT NULL,
    detail      TEXT
);
INSERT INTO "events" VALUES(1,'2026-08-26 15:32:10','a9593032','milestone','Structured memory database created and hourly backup registered','SQLite 3.50.4 via Python. Dump-and-hash backup to private repo dancockrell/memory-db. Scheduled task ClaudeMemoryBackup, hourly.');
INSERT INTO "events" VALUES(2,'2026-08-26T22:52:38','quickgrade-session','milestone','QuickGrade: answer sheet redesign and a visual inspection rig','Added tools/look.js: it renders a page and reports truncated text, collisions, ink too light or thin to survive a photocopier, content escaping its page, and unreadably small type, with annotated and layer screenshots. It immediately found four real defects, including truncated correct answers and a PAGE label running under the first page bubble on every sheet the app had ever printed. Also: questions now print on the answer sheet beside their own bubbles; corner fiducials are registration brackets rather than solid squares, where the arm width is a robustness number and not a taste one (0.5 of the mark measured 0.71 fill against a 0.70 detector threshold and lost corners to noise, 0.58 measures 0.80); the test code is a ten-mark strip instead of thirty pre-filled bubbles; and pages after the first drop the repeated header.');
INSERT INTO "events" VALUES(3,'2026-08-26 15:53:34','dr-companion-session','milestone','Recorded dr-companion invisible dependencies after the Ruby removal','Verified Ruby 4.0.6 at C:\Ruby4Lich5\4.0.6 is present and the three Ruby test suites pass. Added ComfyUI, the FLUX.1-schnell checkpoint (licensing critical), the Genie 4 map XML, and the Node 24 requirement, none of which appear in package.json or any README.');
INSERT INTO "events" VALUES(4,'2026-08-26 15:56:40','a9593032','removal','FLUX.1-dev deleted (16.06 GB, non-commercial licence)','flux1-schnell-fp8 Apache-2.0 retained. dr-companion pins schnell in two files; swapping dev in would make its art pack legally unusable.');
INSERT INTO "events" VALUES(5,'2026-08-26 15:57:08',NULL,'milestone','world-aflame-godot: shipped Skirmish (Snap-inspired simultaneous-reveal ruleset), 1500 keyword-driven generated cards (500/faction), and witness-chain (github.com/dancockrell/witness-chain) -- a standalone dual-signature hash-chain ledger for tamper-evident match records, built for reuse across game projects, not just this one.',NULL);
INSERT INTO "events" VALUES(6,'2026-08-26 16:01:09','a9593032','decision','Co-located dependency warnings generated from the DB','mem export writes DEPENDENCIES.md into project dirs; mem guard writes WHAT-USES-THIS.md into the dependency''s own directory. Guard is the one that would have prevented the Ruby4Lich5 deletion.');
CREATE TABLE facts (
    id          INTEGER PRIMARY KEY,
    category    TEXT NOT NULL CHECK (category IN
                  ('user','project','reference','feedback','trap','tool')),
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    confidence  TEXT DEFAULT 'verified' CHECK (confidence IN
                  ('verified','reported','inferred')),
    source      TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (category, key)
);
INSERT INTO "facts" VALUES(1,'trap','vram-wmi','Win32_VideoController.AdapterRAM reports the RTX 4070 as 4 GB (32-bit overflow). Use nvidia-smi.','verified','2026-08-23','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(2,'trap','crlf-scripts','Heredocs write LF; cmd.exe mis-parses LF-only scripts with misleading errors. Fix with sed then verify with cat -A.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(3,'trap','temp-wipe','Never clear TEMP wholesale on a running system. Broke a Chrome update mid-flight, removing chrome.exe while 268 files stayed intact.','verified','2026-08-26','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(4,'trap','git-noreply','Commits must use the GitHub noreply email or pushes are rejected, and the error does not say so.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(5,'trap','exec-policy','LocalMachine execution policy is AllSigned, blocking npm.ps1. npm works in Git Bash and cmd.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(6,'tool','gpu','RTX 4070, 12012 MB VRAM. Models above ~12 GB spill to shared memory.','verified','2026-08-23','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(7,'trap','file-stripping','Something on this machine strips large files out of untracked dependency trees, and not only in Downloads. 26 Aug 2026: between two runs of the same suite half an hour apart, Downloads/testgrader/tools/node_modules/playwright-core went from a working install to 733 KB with every .js bundle gone and only LICENSE files left, and icudtl.dat disappeared from AppData/Local/ms-playwright/chromium_headless_shell-1234, so Chrome launched and died with ''Invalid file descriptor to ICU data received'' while --version still worked. Git-tracked files were untouched. Recovery: remove node_modules entirely and reinstall (a plain npm install says ''up to date'' from the lockfile without checking file contents, so it does nothing), then npx playwright install chromium --force. Treat an inexplicable module-not-found, or a browser that starts and then dies, as this before suspecting code.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(8,'trap','python-none-on-path','There is no working ''python'' on PATH. python and python3 both resolve to the Windows Store aliases in AppData/Local/Microsoft/WindowsApps, which advertise the Store and exit without executing anything. ''py'' is not installed. The conda install at C:/Users/Admin/anaconda3/python.exe starts under a conda shell but NOT from a child process (it fails with ''Could not find platform independent libraries'') because it needs its own directories on PATH for its DLLs. The one that works from anything is C:/Users/Admin/AppData/Local/Programs/Python/Python313/python.exe, 3.13.15. Any script that shells out to Python must probe a candidate with -c print(1) rather than trust a name, or the fact that a file exists on disk.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(9,'trap','pip-broken','pip on the Python313 install is itself damaged: ''No module named pip._vendor.rich._emoji_codes''. python -m ensurepip --upgrade does not repair it, because ensurepip reads the recorded version, sees pip present and stops. Same family as the file-stripping trap. Consequence: no pip installs on that interpreter until it is repaired, so plan around it rather than through it. Reading a PDF, for instance, was done by rendering it with pdf.js inside headless Chromium instead of installing pypdf.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(10,'trap','heredoc-backslash','Quoted heredocs in the Bash tool still lose backslashes. A JS character class written as [^''BACKSLASH BACKSLASH] arrives with one backslash and the file will not parse; a Python string containing a Windows path loses its escapes and raises a unicodeescape error. Long heredocs are also truncated before their terminator, which surfaces as ''unexpected EOF while looking for matching'' and silently runs nothing in the entire command, including any earlier commands on the same line. Write files in chunks under about 120 lines, prefer forward slashes in paths, and prefer plain string operations to regex escapes in generated scripts.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(11,'trap','crlf-breaks-anchors','Repos here are checked out with CRLF endings, so a patch script that matches a multi-line anchor joined with newline finds nothing, makes no change, and reports success. Detect the ending first and build anchors with it, or splice by line number. This wasted several rounds before it was noticed, because every symptom looked like a wrong anchor string.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(12,'trap','cuda-dll-path','pip nvidia-* wheels put DLLs in site-packages/nvidia/*/bin. os.add_dll_directory is NOT enough - CTranslate2 resolves cuBLAS via its own LoadLibrary. Prepend those dirs to os.environ PATH before importing faster_whisper. Symptom: Library cublas64_12.dll is not found.','verified','2026-08-23','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(13,'trap','uv-python-312','uv venv --python 3.12 fails with a spurious ''missing expected target directory'' error. Pass the interpreter path directly instead.','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(14,'trap','winget-fresh-terminal','winget-installed binaries do not resolve until a NEW terminal opens. They live under AppData/Local/Microsoft/WinGet/Packages/<Publisher.Name>_<hash>/','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(15,'trap','ollama-app-supervises','Killing ''ollama app'' kills the server - the desktop app supervises ''ollama serve'' and port 11434 goes with it.','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(16,'trap','rust-not-on-path','Rust 1.98.0 is installed at %USERPROFILE%/.cargo but is NOT on PATH in Git Bash. Tauri builds need it.','verified','2026-08-26','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(17,'trap','transcript-no-speaker','search_session_transcripts returns user messages, assistant messages and tool output undifferentiated. Never attribute a snippet without checking who produced it.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(18,'trap','verify-outcome-not-output','gh repo create --push prints the repo URL whether or not the push succeeded. Verify state via API, never stdout. Cost: 11 repos reported pushed while empty, 3 times.','verified','2026-08-24','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(19,'feedback','publish-voice','Anything Dan publishes under his own name: no em dashes or middle-dot separators, no delve/leverage/robust/seamless, no reflexive three-item lists. His audience (educators) is the most AI-text-fatigued group in the workforce.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(20,'feedback','claim-standard','Only claim what survives an unannounced test. Dan''s own rule, applied to his languages and skills. Applies to READMEs, commit messages and status reports too.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(21,'trap','npm-test-fail-grep-is-unsound','Counting "^FAIL" lines in npm test output reports 0 failures when a suite CRASHES rather than fails. dr-companion without Ruby on PATH: exit code 1, 313 OK lines, 0 FAIL lines - 90 assertions never ran and the check said clean. Read the exit code. This was used repeatedly before it was caught.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(22,'trap','heredoc-escapes-arrive-mangled','An escape written through a shell heredoc does not survive. \b arrives as an actual backspace (0x08), \s as plain s. The regex still compiles and matches nothing, so it looks like empty data rather than a broken pattern. Hit three times in one session with the trap already documented. Use the file-edit tool for anything containing escapes and verify with charCodeAt.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(23,'trap','deleting-unused-data-is-an-invisible-bet','Deleting a derived artefact that nothing currently reads is a bet that no future feature needs it. The bet is invisible when made and silent when lost. The art daemon deleted each evaluation thumbnail after scoring it - obviously correct, small files, already consumed - and when the scoring scale turned out to be wrong, 172 renders could not be re-measured. Ask what would need this if the thing that produced it were wrong.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(24,'trap','old-data-under-a-new-meaning','Values stored under a key whose meaning later changes are the quietest bug available: nothing errors and every number looks plausible. Measures saved as "stdev" meant raw pixels; the next version read the same key as contrast-normalised. Clear stale values rather than converting them - a converted number carries the same false confidence and is harder to spot. Same shape as a schema change CREATE TABLE IF NOT EXISTS silently skips.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(25,'project','dr-companion-art-pack-size','17,750 room images at a mean 178 KB is about 3.0 GB, against a 72 MB repository. public/rooms is gitignored and needs a release-asset distribution path (issue #8). Creatures (773) and portraits (22) ARE committed at 53 MB because every card and character sheet needs them.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(26,'trap','flux-dev-removed','FLUX.1-dev (non-commercial) was deleted from ComfyUI models on 2026-08-26. Only flux1-schnell-fp8 (Apache-2.0) remains, which is what dr-companion pins. Do not reinstall dev - it would make generated art packs legally unusable.','verified','2026-08-26','2026-08-26 15:56:40','2026-08-26 15:56:40');
INSERT INTO "facts" VALUES(27,'trap','fail-line-counting','Counting FAIL lines in test output is unsound. dr-companion without Ruby: exit code 1, 313 passing assertions, ZERO FAIL lines, 90 assertions never ran. Read the exit code, not the output. Generalises rule 1.','verified','dr-companion-session','2026-08-26 15:56:40','2026-08-26 15:56:40');
INSERT INTO "facts" VALUES(28,'feedback','colocate-warnings','A shared database helps a session that thinks to query it. A README in the directory reaches whoever is standing there deciding what to delete. Both are needed; the second is the one that catches an outsider. Put the warning where the mistake would happen.','verified','dr-companion-session','2026-08-26 15:56:40','2026-08-26 15:56:40');
INSERT INTO "facts" VALUES(29,'feedback','warning-placement','The warning goes where the DESTRUCTIVE ACTION happens - not where the dependency is declared, not where a careful reader would look. A project README reaches someone reading the project. It does not reach someone standing in C:\Ruby4Lich5 deciding if that folder is clutter. Use ''mem guard'' to write WHAT-USES-THIS.md into the dependency''s own directory.','verified','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09');
INSERT INTO "facts" VALUES(30,'trap','stale-warning-worse-than-none','A warning describing a situation that has changed is worse than no warning: it spends the reader''s attention and teaches them the file is stale. Regenerate co-located warnings from the DB rather than hand-maintaining them.','verified','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09');
INSERT INTO "facts" VALUES(31,'trap','burst-vs-recurring','visual-rig ''recurring'' flags a run of events sharing one timestamp as STILL GOING. 14 dr-companion warnings all stamped 22:51:49 were a single injection, not an ongoing fault. Events sharing one timestamp are a burst - needs a rule.','reported','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09');
CREATE TABLE projects (
    name        TEXT PRIMARY KEY,
    path        TEXT,
    repo        TEXT,
    stack       TEXT,
    status      TEXT DEFAULT 'active' CHECK (status IN
                  ('active','paused','archived','published')),
    notes       TEXT,
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "projects" VALUES('dr-companion','C:/Users/Admin/dev/dr-companion','dancockrell/dr-companion','Tauri (Rust + web)','active','Automates Lich. Needs Ruby4Lich5.','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('ghost-front','C:/Users/Admin/dev/ghost-front','dancockrell/ghost-front','single-file HTML','published','WW2 horror platformer','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('raven-classroom','C:/Users/Admin/dev/raven-classroom','dancockrell/raven-classroom','HTML + Apps Script','published','Reader engine behind Raven/Magi/Long Night','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('quickgrade','C:/Users/Admin/Downloads/testgrader','dancockrell/quickgrade','PWA','published','Offline paper grader; student data never leaves device','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('world-aflame','C:/Users/Admin/dev/world-aflame','dancockrell/world-aflame','HTML + WebRTC','archived','Superseded by world-aflame-godot per Dan (2026-08-26): ''everything else is deprecated and archived.'' Original 3-faction web/JS card game; repo/Pages left live as-is, no further development planned here.','2026-08-26 15:56:57');
INSERT INTO "projects" VALUES('longnight','C:/Users/Admin/dev/longnight','dancockrell/longnight','canvas RPG','active','Synthesised orchestra, no audio downloads','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('world-aflame-godot','C:/Users/Admin/dev/world-aflame-godot',NULL,NULL,'published','Active development. Godot 4.7.2 (Standard/non-Mono build required for Web export -- Mono build has zero Web templates). Two rulesets: Classic (turn-based, faithful GDScript port of the web version''s engine + all 150 cards, live-hosted, P2P via NetManager) and Skirmish (new, Snap-inspired simultaneous-reveal mode, 1500 generated keyword-driven cards, engine-verified but UI still landing). Hosted at https://dancockrell.github.io/world-aflame-godot/ via gh-pages branch.','2026-08-26 15:58:37');
CREATE INDEX idx_facts_category ON facts(category);
CREATE INDEX idx_events_ts   ON events(ts);
CREATE INDEX idx_events_kind ON events(kind);
CREATE TRIGGER facts_touch
AFTER UPDATE ON facts FOR EACH ROW
BEGIN
    UPDATE facts SET updated_at = datetime('now') WHERE id = OLD.id;
END;
CREATE TRIGGER projects_touch
AFTER UPDATE ON projects FOR EACH ROW
BEGIN
    UPDATE projects SET updated_at = datetime('now') WHERE name = OLD.name;
END;
COMMIT;