BEGIN TRANSACTION;
CREATE TABLE dependencies (
    id          INTEGER PRIMARY KEY,
    project     TEXT NOT NULL,
    name        TEXT NOT NULL,
    location    TEXT,
    source_url  TEXT,
    why         TEXT NOT NULL,
    critical    INTEGER NOT NULL DEFAULT 1, updated_at TEXT, check_cmd TEXT,
    UNIQUE (project, name),
    FOREIGN KEY (project) REFERENCES projects(name) ON DELETE CASCADE
);
INSERT INTO "dependencies" VALUES(1,'dr-companion','Ruby4Lich5','C:/Ruby4Lich5','https://github.com/elanthia-online/lich-5/releases','Lich runs on Ruby; dr-companion automates Lich. Captured in no manifest.',1,'2026-08-26 16:28:33','ls "C:/Ruby4Lich5/4.0.6/bin/ruby.exe" && echo PRESENT');
INSERT INTO "dependencies" VALUES(2,'dr-companion','Genie4','C:/Genie4/Maps',NULL,'ONLY the Maps subdirectory matters: 85 XML files of twenty years of hand cartography that no package manager can restore. Deleting it breaks nothing today because the built JSON is committed - it means the map can never be rebuilt or corrected. Silent, months later.',1,'2026-08-26 16:28:33','ls "C:/Genie4/Maps"/*.xml | wc -l   # expect 85');
INSERT INTO "dependencies" VALUES(3,'quickgrade','playwright + chromium browser cache','Downloads/testgrader/tools/node_modules and AppData/Local/ms-playwright','https://playwright.dev','The whole 21-suite harness is Playwright driving headless Chromium. tools/package.json names playwright, but nothing records that the browser binaries live in a separate machine-wide cache that can be stripped independently of node_modules. Both have to be present: npm install, then npx playwright install chromium.',1,'2026-08-26 16:18:23',NULL);
INSERT INTO "dependencies" VALUES(4,'quickgrade','CPython 3.13','AppData/Local/Programs/Python/Python313/python.exe',NULL,'build.py regenerates sw.js and the single-file QuickGrade.html, and the build test fails without it. No manifest names an interpreter, and the obvious names on PATH are Store aliases that do nothing. See trap python-none-on-path.',1,'2026-08-26 16:18:23',NULL);
INSERT INTO "dependencies" VALUES(5,'dr-companion','ComfyUI','http://127.0.0.1:8188','https://github.com/comfyanonymous/ComfyUI','The whole art pipeline talks to it over HTTP. tools/art-daemon.mjs waits for it rather than exiting, so a missing ComfyUI looks like a daemon that is running and producing nothing. Needs the ImageScale and SaveImage nodes, which the daemon uses to emit a thumbnail it scores itself on.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(6,'dr-companion','FLUX.1-schnell fp8 checkpoint','C:\Users\Admin\AppData\Local\Comfy-Desktop\ComfyUI-Shared\models\checkpoints','https://huggingface.co/black-forest-labs/FLUX.1-schnell','schnell is Apache 2.0 and puts no conditions on its output, which is the entire reason it and not dev: the art pack can be shipped commercially and given to Simutronics. FLUX.1-dev is the trap. It is the better-known model and what most guides reach for, and it is NON-COMMERCIAL: one image rendered with it would make the whole pack legally unusable. It was on this machine and was deleted 26 Aug 2026, so there is nothing to swap in by accident today. The checkpoint is pinned in tools/art-daemon.mjs and tools/art-run.mjs to guard against it being downloaded again, which is now the likely way this goes wrong.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(7,'dr-companion','Genie 4 map XML','C:\Genie4\Maps','https://www.playdragonrealms.com/','85 XML files, the community cartography every map in dr-companion is built from: 17,750 rooms, 42,866 exits, 3,174 named places, and the 310 gateways linking one zone to the next. tools/build-map.mjs reads them into src/data/map. The built JSON is committed, so deleting these breaks nothing today and permanently prevents the map being rebuilt or corrected. Silent failure, months later, the first time someone needs to regenerate.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(8,'dr-companion','Node 24 or newer','C:\Program Files\nodejs','https://nodejs.org/','The test suite imports TypeScript directly (tools/trail-test.mjs and tools/flow-test.mjs import from src/lib/*.ts) and relies on native type stripping. On an older Node those suites do not run.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(9,'dr-companion','Python 3.13','C:\Users\Admin\AppData\Local\Programs\Python\Python313','https://www.python.org/','Not used by the app. Recorded because `python` on PATH resolves to the Microsoft Store stub and fails with Permission denied, which reads as "Python is missing" when it is installed. Use the full path.',0,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(10,'world-aflame-godot','Public STUN server (stun.l.google.com:19302)','hardcoded in scripts/net/net_manager.gd, ICE_SERVERS const',NULL,'NAT traversal for serverless P2P WebRTC play -- no manifest records this since it''s an external network dependency, not a package. No fallback if Google''s STUN server ever goes away or blocks this traffic.',1,'2026-08-26 16:18:23',NULL);
INSERT INTO "dependencies" VALUES(11,'world-aflame-godot','Godot 4.7.2 Standard (non-Mono) build','C:\Users\Admin\AppData\Local\Programs\Godot\Standard',NULL,'Mono build has zero Web export templates -- this project is pure GDScript specifically so it can use the Standard build and export to Web. Separate install from the Mono build at ...\Godot\Godot_v4.7.2-stable_mono_win64, which is not used by this project.',1,'2026-08-26 16:18:23',NULL);
INSERT INTO "dependencies" VALUES(12,'magi-reader-engine','magi art and audio source folders','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\magi-itch-*',NULL,'The Gift of the Magi''s 224 art files and 519 recordings exist on this disk only. No single magi-itch-* folder is complete (199, 190, 183 of 224); only the union is, and tools/copy-assets.mjs takes the union across seven folders. They are committed to a local repo at C:\Users\Admin\dev\magi-reader whose GitHub remote was DELETED, so committed does not mean backed up: git ls-remote origin fails there. public/art and public/magi-audio are gitignored in magi-app, so nothing reaches GitHub from there either. Verified 26 Aug 2026: 0 magi media files across all three live repos.',1,'2026-08-26 16:38:39','bash "C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\verify-media.sh"');
INSERT INTO "dependencies" VALUES(13,'the-raven-edgar-allan-poe-magi-reader','raven-itch-folder zips','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\raven-itch-folder*.zip',NULL,'HISTORICAL, and now redundant. These four zips held the only copy of The Raven''s 368 narration mp3s and its word-level timings. Verified 26 Aug 2026: 368 committed locally AND 368 present on github.com/dancockrell/the-raven-edgar-allan-poe-magi-reader, so the zips are safe to delete. Do not take that from this row; run the check, which counts both ends every time.',0,'2026-08-26 16:38:39','bash "C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\verify-media.sh"');
CREATE TABLE events (
    id          INTEGER PRIMARY KEY,
    ts          TEXT NOT NULL DEFAULT (datetime('now')),
    session     TEXT,
    kind        TEXT NOT NULL CHECK (kind IN
                  ('decision','error','milestone','removal','install')),
    summary     TEXT NOT NULL,
    detail      TEXT
);
INSERT INTO "events" VALUES(1,'2026-08-26 15:32:10','a9593032','milestone','Structured memory database created and hourly backup registered','SQLite 3.50.4 via Python. Dump-and-hash backup to private repo dancockrell/memory-db. Scheduled task ClaudeMemoryBackup, hourly.');
INSERT INTO "events" VALUES(2,'2026-08-26T22:52:38','quickgrade-session','milestone','QuickGrade: answer sheet redesign and a visual inspection rig','Added tools/look.js: it renders a page and reports truncated text, collisions, ink too light or thin to survive a photocopier, content escaping its page, and unreadably small type, with annotated and layer screenshots. It immediately found four real defects, including truncated correct answers and a PAGE label running under the first page bubble on every sheet the app had ever printed. Also: questions now print on the answer sheet beside their own bubbles; corner fiducials are registration brackets rather than solid squares, where the arm width is a robustness number and not a taste one (0.5 of the mark measured 0.71 fill against a 0.70 detector threshold and lost corners to noise, 0.58 measures 0.80); the test code is a ten-mark strip instead of thirty pre-filled bubbles; and pages after the first drop the repeated header.');
INSERT INTO "events" VALUES(3,'2026-08-26 15:53:34','dr-companion-session','milestone','Recorded dr-companion invisible dependencies after the Ruby removal','Verified Ruby 4.0.6 at C:\Ruby4Lich5\4.0.6 is present and the three Ruby test suites pass. Added ComfyUI, the FLUX.1-schnell checkpoint (licensing critical), the Genie 4 map XML, and the Node 24 requirement, none of which appear in package.json or any README.');
INSERT INTO "events" VALUES(4,'2026-08-26 15:56:40','a9593032','removal','FLUX.1-dev deleted (16.06 GB, non-commercial licence)','flux1-schnell-fp8 Apache-2.0 retained. dr-companion pins schnell in two files; swapping dev in would make its art pack legally unusable.');
INSERT INTO "events" VALUES(5,'2026-08-26 15:57:08',NULL,'milestone','world-aflame-godot: shipped Skirmish (Snap-inspired simultaneous-reveal ruleset), 1500 keyword-driven generated cards (500/faction), and witness-chain (github.com/dancockrell/witness-chain) -- a standalone dual-signature hash-chain ledger for tamper-evident match records, built for reuse across game projects, not just this one.',NULL);
INSERT INTO "events" VALUES(6,'2026-08-26 16:01:09','a9593032','decision','Co-located dependency warnings generated from the DB','mem export writes DEPENDENCIES.md into project dirs; mem guard writes WHAT-USES-THIS.md into the dependency''s own directory. Guard is the one that would have prevented the Ruby4Lich5 deletion.');
INSERT INTO "events" VALUES(7,'2026-08-26 16:02:25',NULL,'decision','The Raven''s narration was recovered from raven-itch-folder zips and committed: 368 mp3 plus a 368-cue WebVTT converted from the original timings.js with zero round-trip failures. The pack''s own AUDIO-NEEDED.md had claimed the audio was gone and unreconstructable; every part of that was false. It is now AUDIO-RECOVERED.md.',NULL);
INSERT INTO "events" VALUES(8,'2026-08-26 16:02:25',NULL,'milestone','magi-reader-engine: feature complete and green. 676 unit tests, 642 e2e across four engines. A book is runtime state rather than a compile-time import, the engine has its own fixture book, and a parity test carries the prototype''s inventory so nothing can be dropped or added without a written decision.',NULL);
INSERT INTO "events" VALUES(9,'2026-08-26 16:09:32','dr-companion-session','error','Nudity gate passed against an empty prompt file','tools/safety-test.mjs runs first in the chain so a regression fails the build before anything else. Pointed at {} it reported all 0 carry it / 0 checked / all passed / exit 0. Fixed in 21e6b06: every none-of-these-are-bad assertion now also asserts the set was not empty, in that suite and six more in the gateway suite.');
INSERT INTO "events" VALUES(10,'2026-08-26 16:12:15','a9593032','decision','guard and review now assert a non-empty denominator','Both reported clean and exit 0 against a wiped database - demonstrated, not reasoned. Now print what was checked and exit 1 when there is nothing to check.');
INSERT INTO "events" VALUES(11,'2026-08-26 16:21:59','a9593032','decision','CLAUDE.md reworked, not appended','Rule 1 rewritten to absorb three overlapping verification lessons into one section with a table of six instances. Header now explicitly invites every session to edit and merge rules, not only append. Numbering declared history, not hierarchy.');
INSERT INTO "events" VALUES(12,'2026-08-26 16:22:44',NULL,'decision','Named a failure class shared across three sessions on 2026-08-26: the check that reports success when it did not execute. Instances: a git audit comparing against origin/<local-branch-name> that does not exist; a test runner counting FAIL lines in output from a suite that crashed; an assertion carrying a term that was always zero; a regex strip that never matched; and the detector written to find them, which found nothing because it read no files. Recorded so the shape is recognisable rather than rediscovered.',NULL);
INSERT INTO "events" VALUES(13,'2026-08-26 16:24:49',NULL,'decision','Declined a peer request to rewrite C:\Users\Admin\.claude\CLAUDE.md. The peer reported that Dan had opened the file to all sessions; that may well be true, but a relayed authorisation is not an authorisation, and CLAUDE.md is the file that governs how every session behaves. Proposed rule text was surfaced to Dan directly instead.',NULL);
INSERT INTO "events" VALUES(14,'2026-08-26 16:26:32','a9593032','decision','Retracted a CLAUDE.md edit invitation sent to three peer sessions','Dan authorised me; I relayed it as authorisation for them. That is permission laundering. Two retractions sent; Magi Reader had already refused and escalated correctly.');
INSERT INTO "events" VALUES(15,'2026-08-26 16:38:39',NULL,'error','Wrote four checks for two dependency rows and every one of them was wrong in the same direction, each printing a plausible zero: a PowerShell wildcard path with -Filter (0 instead of 368); node not on PATH so a tool that never ran reported 0 plates; the wrong extension and directory (.png in public/audio when the files are .webp in public/magi-audio); and git -C failing on a path with an apostrophe, whose error piped into wc -l printed 0 dirty files. Zero is what a broken check says.',NULL);
INSERT INTO "events" VALUES(16,'2026-08-26 16:50:02',NULL,'error','mem review reported six live dependency locations as GONE','Path(loc).exists() was applied to URLs, prose, wildcards and relative paths alike. Fixed with classify_location plus test_classify.py: 10 cases, 2 of which assert real absence, so the suite cannot pass with a classifier that never reports gone. Reported by the Magi Reader session as one row.');
INSERT INTO "events" VALUES(17,'2026-08-26 16:50:02',NULL,'milestone','magi book media confirmed to exist in exactly one place','743 files, 27.5 MB, committed to dev/magi-reader whose remote is a hard 404. Verified against the GitHub tree API for all three magi repos: engine has 5 media under docs/, classroom-toolkit has 0, the-raven has its own 368 in pack/audio. Surfaced to Dan; publishing is his call.');
CREATE TABLE facts (
    id          INTEGER PRIMARY KEY,
    category    TEXT NOT NULL CHECK (category IN
                  ('user','project','reference','feedback','trap','tool')),
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    confidence  TEXT DEFAULT 'verified' CHECK (confidence IN
                  ('verified','reported','inferred')),
    source      TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (category, key)
);
INSERT INTO "facts" VALUES(1,'trap','vram-wmi','Win32_VideoController.AdapterRAM reports the RTX 4070 as 4 GB (32-bit overflow). Use nvidia-smi.','verified','2026-08-23','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(2,'trap','crlf-scripts','Heredocs write LF; cmd.exe mis-parses LF-only scripts with misleading errors. Fix with sed then verify with cat -A.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(3,'trap','temp-wipe','Never clear TEMP wholesale on a running system. Broke a Chrome update mid-flight, removing chrome.exe while 268 files stayed intact.','verified','2026-08-26','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(4,'trap','git-noreply','Commits must use the GitHub noreply email or pushes are rejected, and the error does not say so.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(5,'trap','exec-policy','LocalMachine execution policy is AllSigned, blocking npm.ps1. npm works in Git Bash and cmd.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(6,'tool','gpu','RTX 4070, 12012 MB VRAM. Models above ~12 GB spill to shared memory.','verified','2026-08-23','2026-08-26 15:29:46','2026-08-26 15:29:46');
INSERT INTO "facts" VALUES(7,'trap','file-stripping','Something on this machine strips large files out of untracked dependency trees, and not only in Downloads. 26 Aug 2026: between two runs of the same suite half an hour apart, Downloads/testgrader/tools/node_modules/playwright-core went from a working install to 733 KB with every .js bundle gone and only LICENSE files left, and icudtl.dat disappeared from AppData/Local/ms-playwright/chromium_headless_shell-1234, so Chrome launched and died with ''Invalid file descriptor to ICU data received'' while --version still worked. Git-tracked files were untouched. Recovery: remove node_modules entirely and reinstall (a plain npm install says ''up to date'' from the lockfile without checking file contents, so it does nothing), then npx playwright install chromium --force. Treat an inexplicable module-not-found, or a browser that starts and then dies, as this before suspecting code.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(8,'trap','python-none-on-path','There is no working ''python'' on PATH. python and python3 both resolve to the Windows Store aliases in AppData/Local/Microsoft/WindowsApps, which advertise the Store and exit without executing anything. ''py'' is not installed. The conda install at C:/Users/Admin/anaconda3/python.exe starts under a conda shell but NOT from a child process (it fails with ''Could not find platform independent libraries'') because it needs its own directories on PATH for its DLLs. The one that works from anything is C:/Users/Admin/AppData/Local/Programs/Python/Python313/python.exe, 3.13.15. Any script that shells out to Python must probe a candidate with -c print(1) rather than trust a name, or the fact that a file exists on disk.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(9,'trap','pip-broken','pip on the Python313 install is itself damaged: ''No module named pip._vendor.rich._emoji_codes''. python -m ensurepip --upgrade does not repair it, because ensurepip reads the recorded version, sees pip present and stops. Same family as the file-stripping trap. Consequence: no pip installs on that interpreter until it is repaired, so plan around it rather than through it. Reading a PDF, for instance, was done by rendering it with pdf.js inside headless Chromium instead of installing pypdf.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(10,'trap','heredoc-backslash','Quoted heredocs in the Bash tool still lose backslashes. A JS character class written as [^''BACKSLASH BACKSLASH] arrives with one backslash and the file will not parse; a Python string containing a Windows path loses its escapes and raises a unicodeescape error. Long heredocs are also truncated before their terminator, which surfaces as ''unexpected EOF while looking for matching'' and silently runs nothing in the entire command, including any earlier commands on the same line. Write files in chunks under about 120 lines, prefer forward slashes in paths, and prefer plain string operations to regex escapes in generated scripts.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(11,'trap','crlf-breaks-anchors','Repos here are checked out with CRLF endings, so a patch script that matches a multi-line anchor joined with newline finds nothing, makes no change, and reports success. Detect the ending first and build anchors with it, or splice by line number. This wasted several rounds before it was noticed, because every symptom looked like a wrong anchor string.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38');
INSERT INTO "facts" VALUES(12,'trap','cuda-dll-path','pip nvidia-* wheels put DLLs in site-packages/nvidia/*/bin. os.add_dll_directory is NOT enough - CTranslate2 resolves cuBLAS via its own LoadLibrary. Prepend those dirs to os.environ PATH before importing faster_whisper. Symptom: Library cublas64_12.dll is not found.','verified','2026-08-23','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(13,'trap','uv-python-312','uv venv --python 3.12 fails with a spurious ''missing expected target directory'' error. Pass the interpreter path directly instead.','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(14,'trap','winget-fresh-terminal','winget-installed binaries do not resolve until a NEW terminal opens. They live under AppData/Local/Microsoft/WinGet/Packages/<Publisher.Name>_<hash>/','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(15,'trap','ollama-app-supervises','Killing ''ollama app'' kills the server - the desktop app supervises ''ollama serve'' and port 11434 goes with it.','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01');
INSERT INTO "facts" VALUES(16,'trap','rust-not-on-path','Rust 1.98.0 is installed at %USERPROFILE%/.cargo but is NOT on PATH in Git Bash. Tauri builds need it.','verified','2026-08-26','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(17,'trap','transcript-no-speaker','search_session_transcripts returns user messages, assistant messages and tool output undifferentiated. Never attribute a snippet without checking who produced it.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(18,'trap','verify-outcome-not-output','gh repo create --push prints the repo URL whether or not the push succeeded. Verify state via API, never stdout. Cost: 11 repos reported pushed while empty, 3 times.','verified','2026-08-24','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(19,'feedback','publish-voice','Anything Dan publishes under his own name: no em dashes or middle-dot separators, no delve/leverage/robust/seamless, no reflexive three-item lists. His audience (educators) is the most AI-text-fatigued group in the workforce.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(20,'feedback','claim-standard','Only claim what survives an unannounced test. Dan''s own rule, applied to his languages and skills. Applies to READMEs, commit messages and status reports too.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02');
INSERT INTO "facts" VALUES(21,'trap','npm-test-fail-grep-is-unsound','Counting "^FAIL" lines in npm test output reports 0 failures when a suite CRASHES rather than fails. dr-companion without Ruby on PATH: exit code 1, 313 OK lines, 0 FAIL lines - 90 assertions never ran and the check said clean. Read the exit code. This was used repeatedly before it was caught.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(22,'trap','heredoc-escapes-arrive-mangled','An escape written through a shell heredoc does not survive. \b arrives as an actual backspace (0x08), \s as plain s. The regex still compiles and matches nothing, so it looks like empty data rather than a broken pattern. Hit three times in one session with the trap already documented. Use the file-edit tool for anything containing escapes and verify with charCodeAt.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(23,'trap','deleting-unused-data-is-an-invisible-bet','Deleting a derived artefact that nothing currently reads is a bet that no future feature needs it. The bet is invisible when made and silent when lost. The art daemon deleted each evaluation thumbnail after scoring it - obviously correct, small files, already consumed - and when the scoring scale turned out to be wrong, 172 renders could not be re-measured. Ask what would need this if the thing that produced it were wrong.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(24,'trap','old-data-under-a-new-meaning','Values stored under a key whose meaning later changes are the quietest bug available: nothing errors and every number looks plausible. Measures saved as "stdev" meant raw pixels; the next version read the same key as contrast-normalised. Clear stale values rather than converting them - a converted number carries the same false confidence and is harder to spot. Same shape as a schema change CREATE TABLE IF NOT EXISTS silently skips.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(25,'project','dr-companion-art-pack-size','17,750 room images at a mean 178 KB is about 3.0 GB, against a 72 MB repository. public/rooms is gitignored and needs a release-asset distribution path (issue #8). Creatures (773) and portraits (22) ARE committed at 53 MB because every card and character sheet needs them.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34');
INSERT INTO "facts" VALUES(26,'trap','flux-dev-removed','FLUX.1-dev (non-commercial) was deleted from ComfyUI models on 2026-08-26. Only flux1-schnell-fp8 (Apache-2.0) remains, which is what dr-companion pins. Do not reinstall dev - it would make generated art packs legally unusable.','verified','2026-08-26','2026-08-26 15:56:40','2026-08-26 15:56:40');
INSERT INTO "facts" VALUES(27,'trap','fail-line-counting','Counting FAIL lines in test output is unsound. dr-companion without Ruby: exit code 1, 313 passing assertions, ZERO FAIL lines, 90 assertions never ran. Read the exit code, not the output. Generalises rule 1.','verified','dr-companion-session','2026-08-26 15:56:40','2026-08-26 15:56:40');
INSERT INTO "facts" VALUES(28,'feedback','colocate-warnings','A shared database helps a session that thinks to query it. A README in the directory reaches whoever is standing there deciding what to delete. Both are needed; the second is the one that catches an outsider. Put the warning where the mistake would happen.','verified','dr-companion-session','2026-08-26 15:56:40','2026-08-26 15:56:40');
INSERT INTO "facts" VALUES(29,'feedback','warning-placement','The warning goes where the DESTRUCTIVE ACTION happens - not where the dependency is declared, not where a careful reader would look. A project README reaches someone reading the project. It does not reach someone standing in C:\Ruby4Lich5 deciding if that folder is clutter. Use ''mem guard'' to write WHAT-USES-THIS.md into the dependency''s own directory.','verified','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09');
INSERT INTO "facts" VALUES(30,'trap','stale-warning-worse-than-none','A warning describing a situation that has changed is worse than no warning: it spends the reader''s attention and teaches them the file is stale. Regenerate co-located warnings from the DB rather than hand-maintaining them.','verified','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09');
INSERT INTO "facts" VALUES(31,'trap','burst-vs-recurring','visual-rig ''recurring'' flags a run of events sharing one timestamp as STILL GOING. 14 dr-companion warnings all stamped 22:51:49 were a single injection, not an ongoing fault. Events sharing one timestamp are a burst - needs a rule.','reported','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09');
INSERT INTO "facts" VALUES(32,'trap','PYTHON_ON_PATH_IS_A_STUB','python.exe on PATH is the Windows Store alias at AppData\Local\Microsoft\WindowsApps and fails with ''the file cannot be accessed by the system''. The real interpreter is C:\Users\Admin\AppData\Local\Programs\Python\Python313\python.exe. There is no py launcher.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(33,'trap','POWERSHELL_APOSTROPHE_IN_LEGACY_PATH','The magi-app repo lives under a folder literally named ''Legacy builds and Assets...if you can''''t find something, try here''. The apostrophe in can''''t breaks every single-quoted PowerShell string and every inline node -e that embeds the path. Use a script file and pass the path as an argument, or Join-Path with a variable. This broke four separate commands in one session.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(34,'trap','NODE_INLINE_EVAL_MANGLES_REGEX','node -e through PowerShell mangles backticks, dollar signs and backslashes, so regex literals and template strings arrive corrupted. A .mjs file run by path is the only reliable route. Symptom: ''Unterminated regexp literal'' or a replacement that silently matches nothing.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(35,'trap','RAVEN_AUDIO_LIVES_IN_ZIPS','The Raven''s 368 narration mp3s and its word-level timings.js were only ever inside raven-itch-folder.zip / _2 / _4 / _6 beside the magi-app folder. They are now committed to dancockrell/the-raven-edgar-allan-poe-magi-reader under pack/audio and pack/cues. Before deleting any raven-itch-folder zip, confirm that repo still has 368 files in pack/audio.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(36,'trap','MAGI_MEDIA_IS_SPREAD_ACROSS_FOLDERS','No single folder holds a complete set of Magi''s art. magi-itch-ui has 29 of 54 plates, magi-itch-guide2-clean 20, magi-itch-improved 13. Only the union is whole, which is why tools/copy-assets.mjs now searches seven sources and takes the union instead of naming one folder.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(37,'trap','PLAYWRIGHT_ITCH_TEST_NEEDS_ITS_OWN_RUN','magi-app''s e2e/itch.spec.js stands up two extra HTTP servers and loads the built game in an iframe. Under four workers it times out even at 90s; alone it takes 12.6s. Tagged @serial, run by npm run e2e:serial, and verify:full runs it FIRST because running it after the parallel suite fails on a warm machine. Do not answer this by raising the timeout again; that was tried twice.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(38,'trap','MAGI_APP_IS_BACKED_UP','magi-app in the Legacy folder DOES have a remote: github.com/dancockrell/magi-reader-engine, branch master pushing to main, 44 commits, clean. A report that it has no remote and zero commits was wrong, probably from running git in the wrong directory. Verify with git config --get remote.origin.url before ''rescuing'' it.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25');
INSERT INTO "facts" VALUES(39,'feedback','generated-warnings-need-correct-source','Generating a warning file from a database is right - it cannot drift - but it only moves the accuracy problem to the row. Two of the dr-companion rows were wrong within an hour: one said the project ''works alongside'' Genie when it only reads its map files, and one said FLUX.1-dev was on this machine after it had been deleted. Fix the row, not the file. And treat a thin row as a bug, because the generated file can only be as specific as its source.','verified','dr-companion-session','2026-08-26 16:03:10','2026-08-26 16:03:10');
INSERT INTO "facts" VALUES(40,'trap','git-audit-branch-mismatch','My repo audit reported magi-app as having 0 commits and no remote. Wrong: it is dancockrell/magi-reader-engine with 44 commits, clean. The bug was mine - I computed unpushed as ''origin/$branch..HEAD'' using the LOCAL branch name. magi-app is master locally pushing to main, so origin/master does not exist and the check silently returned nothing. Compare against the remote''s actual default branch.','verified','2026-08-26','2026-08-26 16:05:55','2026-08-26 16:05:55');
INSERT INTO "facts" VALUES(41,'trap','silent-skip-hides-gaps','A skip counted as housekeeping hides real gaps. mem guard reported ''7 skipped (URLs and non-directories)'' while the FLUX licence dependency - the one with a legal consequence - had no warning file anywhere. Skips must be loud and itemised.','verified','dr-companion-session','2026-08-26 16:05:55','2026-08-26 16:05:55');
INSERT INTO "facts" VALUES(42,'trap','generated-from-bad-row','Generating a warning from a database moves the accuracy problem to the row, it does not remove it. The file cannot drift from the row; the row can still be wrong or thin. A one-line ''why'' produces a warning nobody stops for - same defect as an empty warning, harder to see.','verified','dr-companion-session','2026-08-26 16:05:55','2026-08-26 16:05:55');
INSERT INTO "facts" VALUES(43,'trap','legacy-folder-apostrophe','The Legacy folder name contains an apostrophe ("...if you can''t find something..."). It breaks every single-quoted PowerShell string and every inline node -e touching that path. Use double quotes or a variable.','verified','magi-reader-session','2026-08-26 16:05:55','2026-08-26 16:05:55');
INSERT INTO "facts" VALUES(45,'trap','negative-result-vs-absent-result','The commonest bug across three sessions in one day: a check reports success because it never ran. A negative result and an absent result are indistinguishable unless you make them different. Four instances, all silent: counting FAIL lines in a suite that crashed (exit 1, zero FAIL lines, 90 assertions never run); asserting none of these prompts are missing the clause against an EMPTY file (all 0 carry it, passed - and that is the gate that runs first to stop a nudity regression); a dependency guard reporting 7 skipped where the skips WERE the unprotected paths; a git check against origin/master in a repo pushing to main. Fix: prove the work happened. Read exit codes. Assert a floor on how many things were checked, set well below the real count. Print the count. Make skips loud and non-zero-exit.','verified','dr-companion-session','2026-08-26 16:09:32','2026-08-26 16:09:32');
INSERT INTO "facts" VALUES(46,'trap','negative-vs-absent-result','A negative result and an absent result print identically unless you make them different, and the absent one looks like success. Four instances in one session: safety-test.mjs passed against an empty prompt file; a FAIL-line count reported clean on a crashed suite; mem guard reported ''0 written'' against a wiped dependencies table; a git audit reported ''no remote'' when origin/$branch did not exist. Fix: assert the denominator is non-empty and print what was checked.','verified','dr-companion-session','2026-08-26 16:12:15','2026-08-26 16:12:15');
INSERT INTO "facts" VALUES(47,'feedback','denominator-must-be-the-fragile-thing','Count the check against the thing that goes to zero when the mechanism fails, not the thing that stays constant. ''No humanoid is undressed'' is true and meaningless if the humanoid detector classified nothing. Denominator = humanoids found, not creatures total.','verified','dr-companion-session','2026-08-26 16:12:15','2026-08-26 16:12:15');
INSERT INTO "facts" VALUES(48,'feedback','rules-recognise-they-do-not-prevent','Writing a rule down does not create the reflex. In one session I wrote ''verify the outcome not the output'' then broke it twice more; DR Companion wrote ''a stale warning is worse than none'' then left one for an hour. What actually caught both was another session inspecting the artefact. Rules help recognise a failure that is already in front of you. Cross-checking is what prevents it.','verified','dr-companion-session','2026-08-26 16:12:15','2026-08-26 16:12:15');
INSERT INTO "facts" VALUES(49,'reference','witness-chain-renamed','witness-chain was renamed to project-42-blockchain. Repo: dancockrell/project-42-blockchain. Any earlier reference to witness-chain means this.','verified','downloads-f5','2026-08-26 16:17:49','2026-08-26 16:17:49');
INSERT INTO "facts" VALUES(50,'trap','dual-signature-collusion','Dual-signature verification does not prevent collusion. Two cooperating signers can co-sign each other''s records indefinitely and dominate aggregate statistics (win-rate mining) without ever failing verification. Any consumer aggregating across a chain needs a DISTINCT-COSIGNER count, not a signature count. Raised against project-42-blockchain issue #1 by the World Aflame session.','verified','downloads-f5','2026-08-26 16:17:49','2026-08-26 16:17:49');
INSERT INTO "facts" VALUES(51,'trap','pipe-discards-exit-code','A shell pipeline reports the exit status of its LAST command. So `cmd 2>&1 | tail -1 || fallback` never runs the fallback, because tail always succeeds. Every git push in one dr-companion session used that pattern and the rebase fallback was dead code across 22 commits. It cost nothing only because the real check was comparing local and origin SHAs afterwards. Redirect to a file and test $?, or set pipefail. Two sessions hit this independently on 26 Aug 2026.','verified','dr-companion-session','2026-08-26 16:18:08','2026-08-26 16:18:08');
INSERT INTO "facts" VALUES(52,'trap','generated-file-not-regenerated','Generating a doc from a database removes drift only while something re-runs the generator. dr-companion DEPENDENCIES.md carried a claim that a model was on this machine for an hour after the database row had been corrected and the model deleted. The row was right; nothing had re-run export. Consider running the generator on any write to the source table, or flagging a generated file older than the row it came from.','verified','dr-companion-session','2026-08-26 16:18:08','2026-08-26 16:18:08');
INSERT INTO "facts" VALUES(53,'trap','python-backslash-U','Windows paths in Python source break on \U (C:\Users) and \x etc. Use r''...'' raw strings or forward slashes. Hit this twice in one session INCLUDING while writing the note about it.','verified','2026-08-26','2026-08-26 16:21:59','2026-08-26 16:21:59');
INSERT INTO "facts" VALUES(54,'trap','pipe-eats-exit-status','Never read $? after a pipe - it reports the LAST command''s status. ''cmd | tail'' always succeeds. Killed a git push retry fallback for 22 commits (DR Companion) and nearly made me file a working fix as broken.','verified','dr-companion-session','2026-08-26 16:21:59','2026-08-26 16:21:59');
INSERT INTO "facts" VALUES(55,'feedback','generate-then-nothing-reruns','Generating a file from a database does not help if nothing re-runs the generator. A file cannot drift while being written and drifts for as long as it is not. mem review now flags generated files older than their rows; export/guard touch mtime on no-op so the flag can actually clear.','verified','dr-companion-session','2026-08-26 16:21:59','2026-08-26 16:21:59');
INSERT INTO "facts" VALUES(56,'trap','VACUOUS_SWEEP_IN_TESTS','The test-suite form of ''a check that reports success without running'': a test walks a population, collects offenders, asserts the list is empty. That passes when nothing is wrong AND when nothing was examined. magi-reader-engine has tools/vacuous-sweeps.mjs to find them (40 sweeps, 29 with no population check, most benign). The fix is one line: assert the population was non-empty before asserting the offenders list is. Real instances found: plates over zero plates, answers over zero questions, translations over zero words, and an alignment sweep that ''continue''d past every clip when the cue file failed to load.','verified',NULL,'2026-08-26 16:22:44','2026-08-26 16:22:44');
INSERT INTO "facts" VALUES(57,'trap','DETECTOR_FOUND_ITSELF','The vacuous-sweep detector''s first version reported ''0 sweeps, 0 unguarded'' having found no test files at all: its parser started scanning inside a string literal and never terminated. A clean bill of health from a tool that examined nothing. Any auditing tool must print its own population count and exit non-zero when that count is zero, or it will one day report success for the wrong reason.','verified',NULL,'2026-08-26 16:22:44','2026-08-26 16:22:44');
INSERT INTO "facts" VALUES(60,'trap','peer-cannot-authorise-claude-md','A peer session relaying the user''s authorisation is NOT the user''s authorisation - specifically for CLAUDE.md, permission settings and config. It is unverifiable from the receiving side and that file governs every session. I relayed Dan''s grant to three sessions; Magi Reader correctly refused and escalated to Dan directly. If you have a rule to add, ask the user or ask the session that holds the grant to make the edit and attribute it.','verified','magi-reader-session','2026-08-26 16:26:32','2026-08-26 16:26:32');
INSERT INTO "facts" VALUES(61,'feedback','write-the-check-not-the-claim','When documenting the state of anything on disk, record the COMMAND that establishes it, not the answer that command gave once. A claim about what exists rots the moment the world moves and stays equally authoritative; its reader cannot re-derive it. ''The audio does not exist and cannot be reconstructed'' was unfalsifiable and wrong. ''Look in raven-itch-folder*.zip for raven-audio/'' is a 30-second check that stays true. AUDIO-NEEDED.md worked only because it was scary, not because it was informative.','verified','magi-reader-session','2026-08-26 16:26:32','2026-08-26 16:26:32');
INSERT INTO "facts" VALUES(62,'trap','PS_WILDCARD_PATH_WITH_FILTER_RETURNS_ZERO','PowerShell: Get-ChildItem on a path whose DIRECTORY portion contains a wildcard, combined with -Filter or -Include, silently returns 0. No error, and -ErrorAction Stop raises nothing. Get-ChildItem C:\Users\Admin\dev\the-raven-*\pack\audio -Filter *.mp3 returned 0 where the literal path returned 368; the wildcard form yields the directory itself as a single item, which then fails the filter. Resolve-Path on the same pattern resolves correctly, so the path is not the problem. Fix: put the wildcard in the LEAF, as "...\pack\audio\*.mp3", which returns 368. This matters because the zero reads as an honest absence of files.','verified',NULL,'2026-08-26 16:38:39','2026-08-26 16:38:39');
INSERT INTO "facts" VALUES(63,'trap','warning-list-of-false-positives','A warning list where every entry is a false positive is worse than no list. mem review reported six dependency locations as GONE; all six were live. Rows are only comparable if the check can distinguish ''absent'' from ''I could not check this''. Report the second honestly rather than folding it into the first.','verified','found by Magi Reader session, one row; six on inspection','2026-08-26 16:49:42','2026-08-26 16:49:42');
INSERT INTO "facts" VALUES(64,'trap','github-404-means-deleted-not-renamed','GitHub 301-redirects a renamed repository, so an old URL keeps working. A hard 404 from gh api repos/OWNER/NAME therefore means the repo was DELETED, not renamed. Use this to tell the two apart before assuming content moved to a similarly-named repo.','verified','dev/magi-reader remote 404 while magi-reader-engine exists','2026-08-26 16:49:43','2026-08-26 16:49:43');
INSERT INTO "facts" VALUES(65,'trap','guess-last-look-first','Order heuristics after facts. classify_location used a '' and '' substring to detect prose, which matched a real directory named ''Legacy builds and Assets...'' and demoted a checkable path to unchecked. Ask the filesystem first; apply guesswork only to strings that already failed to resolve.','verified','self-inflicted while fixing warning-list-of-false-positives','2026-08-26 16:49:43','2026-08-26 16:49:43');
INSERT INTO "facts" VALUES(66,'project','magi-media-single-copy','The magi book media (224 art + 519 audio = 743 files, 27.5 MB) is committed only to C:\Users\Admin\dev\magi-reader, whose GitHub remote dancockrell/magi-reader was DELETED (hard 404). magi-reader-engine holds 5 media files, all under docs/; magi-reader-classroom-toolkit holds 0. That working tree also has 94 uncommitted files. One disk, no remote. Dan''s call whether to publish.','verified','gh api git/trees recursive on all three repos, 2026-08-26','2026-08-26 16:49:43','2026-08-26 16:49:43');
CREATE TABLE projects (
    name        TEXT PRIMARY KEY,
    path        TEXT,
    repo        TEXT,
    stack       TEXT,
    status      TEXT DEFAULT 'active' CHECK (status IN
                  ('active','paused','archived','published')),
    notes       TEXT,
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "projects" VALUES('dr-companion','C:/Users/Admin/dev/dr-companion','dancockrell/dr-companion','Tauri (Rust + web)','active','Automates Lich. Needs Ruby4Lich5.','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('ghost-front','C:/Users/Admin/dev/ghost-front','dancockrell/ghost-front','single-file HTML','published','WW2 horror platformer','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('raven-classroom','C:/Users/Admin/dev/raven-classroom','dancockrell/raven-classroom','HTML + Apps Script','published','Reader engine behind Raven/Magi/Long Night','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('quickgrade','C:/Users/Admin/Downloads/testgrader','dancockrell/quickgrade','PWA','published','Offline paper grader; student data never leaves device','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('world-aflame','C:/Users/Admin/dev/world-aflame','dancockrell/world-aflame','HTML + WebRTC','archived','Superseded by world-aflame-godot per Dan (2026-08-26): ''everything else is deprecated and archived.'' Original 3-faction web/JS card game; repo/Pages left live as-is, no further development planned here.','2026-08-26 15:56:57');
INSERT INTO "projects" VALUES('longnight','C:/Users/Admin/dev/longnight','dancockrell/longnight','canvas RPG','active','Synthesised orchestra, no audio downloads','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('world-aflame-godot','C:/Users/Admin/dev/world-aflame-godot',NULL,NULL,'published','Active development. Godot 4.7.2 (Standard/non-Mono build required for Web export -- Mono build has zero Web templates). Two rulesets: Classic (turn-based, faithful GDScript port of the web version''s engine + all 150 cards, live-hosted, P2P via NetManager) and Skirmish (new, Snap-inspired simultaneous-reveal mode, 1500 generated keyword-driven cards, engine-verified but UI still landing). Hosted at https://dancockrell.github.io/world-aflame-godot/ via gh-pages branch.','2026-08-26 15:58:37');
INSERT INTO "projects" VALUES('magi-reader-engine','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\magi-app','https://github.com/dancockrell/magi-reader-engine','React 19, Vite 8, Playwright, Google Apps Script','active','The illustrated reading engine for language classrooms, named after The Gift of the Magi. One engine, many books: a book is a pack under src/books and src/engine.test.js fails if engine code names a title, an author or a book id. 676 unit tests, 642 e2e across four browser engines. Still in Downloads rather than dev, against the usual rule.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('the-gift-of-the-magi-o-henry-magi-reader','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\magi-app\src\books\magi','https://github.com/dancockrell/the-gift-of-the-magi-o-henry-magi-reader','book pack: JSON plus media','active','Still inside the engine repository, not yet split out. Blocked on step 2 of PLAN.md, the bring-your-own-pack contract. The engine now has its own fixture book so the tests no longer need this one.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('the-raven-edgar-allan-poe-magi-reader','C:\Users\Admin\dev\the-raven-edgar-allan-poe-raven-reader','https://github.com/dancockrell/the-raven-edgar-allan-poe-magi-reader','book pack: JSON, 368 mp3, WebVTT','active','Poe''s poem as a Magi Reader book. Narration and word-level cues recovered from raven-itch-folder zips and committed. Note the folder on disk still says raven-reader while the repo says magi-reader.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('magi-reader-classroom-toolkit',NULL,'https://github.com/dancockrell/magi-reader-classroom-toolkit',NULL,'archived','Was raven-classroom, renamed 2026-08-26. Provenance, not a product: the toolkit the engine grew out of, still holding the QR check-in page and the voice generators. Its old description called it the engine behind Raven, Magi and The Long Night, which was wrong on both counts: it is not the engine, and it has nothing to do with The Long Night.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('project-42-blockchain','C:/Users/Admin/dev/project-42-blockchain','dancockrell/project-42-blockchain','GDScript library','active','Dual-signature hash-chain ledger, MIT, no server or currency. Renamed from witness-chain. Consumed by world-aflame-godot for Elo. Open issue #1 requests key persistence, DAG timestamp-ordered iteration, an append() payload-validator hook, and a distinct-cosigner-count helper.','2026-08-26 16:17:49');
CREATE INDEX idx_facts_category ON facts(category);
CREATE INDEX idx_events_ts   ON events(ts);
CREATE INDEX idx_events_kind ON events(kind);
CREATE TRIGGER facts_touch
AFTER UPDATE ON facts FOR EACH ROW
BEGIN
    UPDATE facts SET updated_at = datetime('now') WHERE id = OLD.id;
END;
CREATE TRIGGER projects_touch
AFTER UPDATE ON projects FOR EACH ROW
BEGIN
    UPDATE projects SET updated_at = datetime('now') WHERE name = OLD.name;
END;
CREATE TRIGGER deps_touch
        AFTER UPDATE ON dependencies FOR EACH ROW
        BEGIN UPDATE dependencies SET updated_at = datetime('now') WHERE id = OLD.id; END;
CREATE TRIGGER deps_stamp
        AFTER INSERT ON dependencies FOR EACH ROW WHEN NEW.updated_at IS NULL
        BEGIN UPDATE dependencies SET updated_at = datetime('now') WHERE id = NEW.id; END;
COMMIT;