BEGIN TRANSACTION;
CREATE TABLE dependencies (
    id          INTEGER PRIMARY KEY,
    project     TEXT NOT NULL,
    name        TEXT NOT NULL,
    location    TEXT,
    source_url  TEXT,
    why         TEXT NOT NULL,
    critical    INTEGER NOT NULL DEFAULT 1, updated_at TEXT, check_cmd TEXT,
    UNIQUE (project, name),
    FOREIGN KEY (project) REFERENCES projects(name) ON DELETE CASCADE
);
INSERT INTO "dependencies" VALUES(1,'dr-companion','Ruby4Lich5','C:/Ruby4Lich5','https://github.com/elanthia-online/lich-5/releases','Lich runs on Ruby; dr-companion automates Lich. Captured in no manifest.',1,'2026-08-26 16:28:33','ls "C:/Ruby4Lich5/4.0.6/bin/ruby.exe" && echo PRESENT');
INSERT INTO "dependencies" VALUES(2,'dr-companion','Genie4','C:/Genie4/Maps',NULL,'ONLY the Maps subdirectory matters: 85 XML files of twenty years of hand cartography that no package manager can restore. Deleting it breaks nothing today because the built JSON is committed - it means the map can never be rebuilt or corrected. Silent, months later.',1,'2026-08-26 16:28:33','ls "C:/Genie4/Maps"/*.xml | wc -l   # expect 85');
INSERT INTO "dependencies" VALUES(3,'quickgrade','playwright (node package)','C:/Users/Admin/Downloads/testgrader/tools/node_modules','https://playwright.dev','The whole test harness is Playwright driving headless Chromium. tools/package.json names the package but nothing records that the browser binaries live in a separate machine-wide cache, listed as its own row. Both must be present.',1,'2026-08-26 17:01:06',NULL);
INSERT INTO "dependencies" VALUES(4,'quickgrade','CPython 3.13','C:/Users/Admin/AppData/Local/Programs/Python/Python313',NULL,'build.py regenerates sw.js and the single-file QuickGrade.html, and the build check fails without it. No manifest names an interpreter, and the obvious names on PATH are Store aliases that execute nothing. The binary is python.exe inside this directory. See trap python-none-on-path.',1,'2026-08-26 17:01:06',NULL);
INSERT INTO "dependencies" VALUES(5,'dr-companion','ComfyUI','http://127.0.0.1:8188','https://github.com/comfyanonymous/ComfyUI','The whole art pipeline talks to it over HTTP. tools/art-daemon.mjs waits for it rather than exiting, so a missing ComfyUI looks like a daemon that is running and producing nothing. Needs the ImageScale and SaveImage nodes, which the daemon uses to emit a thumbnail it scores itself on.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(6,'dr-companion','FLUX.1-schnell fp8 checkpoint','C:\Users\Admin\AppData\Local\Comfy-Desktop\ComfyUI-Shared\models\checkpoints','https://huggingface.co/black-forest-labs/FLUX.1-schnell','schnell is Apache 2.0 and puts no conditions on its output, which is the entire reason it and not dev: the art pack can be shipped commercially and given to Simutronics. FLUX.1-dev is the trap. It is the better-known model and what most guides reach for, and it is NON-COMMERCIAL: one image rendered with it would make the whole pack legally unusable. It was on this machine and was deleted 26 Aug 2026, so there is nothing to swap in by accident today. The checkpoint is pinned in tools/art-daemon.mjs and tools/art-run.mjs to guard against it being downloaded again, which is now the likely way this goes wrong.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(7,'dr-companion','Genie 4 map XML','C:\Genie4\Maps','https://www.playdragonrealms.com/','85 XML files, the community cartography every map in dr-companion is built from: 17,750 rooms, 42,866 exits, 3,174 named places, and the 310 gateways linking one zone to the next. tools/build-map.mjs reads them into src/data/map. The built JSON is committed, so deleting these breaks nothing today and permanently prevents the map being rebuilt or corrected. Silent failure, months later, the first time someone needs to regenerate.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(8,'dr-companion','Node 24 or newer','C:\Program Files\nodejs','https://nodejs.org/','The test suite imports TypeScript directly (tools/trail-test.mjs and tools/flow-test.mjs import from src/lib/*.ts) and relies on native type stripping. On an older Node those suites do not run.',1,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(9,'dr-companion','Python 3.13','C:\Users\Admin\AppData\Local\Programs\Python\Python313','https://www.python.org/','Not used by the app. Recorded because `python` on PATH resolves to the Microsoft Store stub and fails with Permission denied, which reads as "Python is missing" when it is installed. Use the full path.',0,'2026-08-26 16:19:21',NULL);
INSERT INTO "dependencies" VALUES(10,'world-aflame-godot','Public STUN server (stun.l.google.com:19302)','hardcoded in scripts/net/net_manager.gd, ICE_SERVERS const',NULL,'NAT traversal for serverless P2P WebRTC play -- no manifest records this since it''s an external network dependency, not a package. No fallback if Google''s STUN server ever goes away or blocks this traffic.',1,'2026-08-26 16:18:23',NULL);
INSERT INTO "dependencies" VALUES(11,'world-aflame-godot','Godot 4.7.2 Standard (non-Mono) build','C:\Users\Admin\AppData\Local\Programs\Godot\Standard',NULL,'Mono build has zero Web export templates -- this project is pure GDScript specifically so it can use the Standard build and export to Web. Separate install from the Mono build at ...\Godot\Godot_v4.7.2-stable_mono_win64, which is not used by this project.',1,'2026-08-26 16:18:23',NULL);
INSERT INTO "dependencies" VALUES(12,'magi-reader-engine','magi art and audio source folders','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\magi-itch-*',NULL,'The Gift of the Magi''s 224 art files and 519 recordings exist on this disk only. No single magi-itch-* folder is complete (199, 190, 183 of 224); only the union is, and tools/copy-assets.mjs takes the union across seven folders. They are committed to a local repo at C:\Users\Admin\dev\magi-reader whose GitHub remote was DELETED, so committed does not mean backed up: git ls-remote origin fails there. public/art and public/magi-audio are gitignored in magi-app, so nothing reaches GitHub from there either. Verified 26 Aug 2026: 0 magi media files across all three live repos.',1,'2026-08-26 16:38:39','bash "C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\verify-media.sh"');
INSERT INTO "dependencies" VALUES(13,'the-raven-edgar-allan-poe-magi-reader','raven-itch-folder zips','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\raven-itch-folder*.zip',NULL,'HISTORICAL, and now redundant. These four zips held the only copy of The Raven''s 368 narration mp3s and its word-level timings. Verified 26 Aug 2026: 368 committed locally AND 368 present on github.com/dancockrell/the-raven-edgar-allan-poe-magi-reader, so the zips are safe to delete. Do not take that from this row; run the check, which counts both ends every time.',0,'2026-08-26 16:38:39','bash "C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\verify-media.sh"');
INSERT INTO "dependencies" VALUES(14,'quickgrade','chromium browser cache (playwright)','C:/Users/Admin/AppData/Local/ms-playwright','https://playwright.dev','Where playwright keeps the browsers it downloads. Separate from node_modules and strippable independently of it: on 26 Aug 2026 icudtl.dat vanished from here and Chrome launched then died while --version still worked. Restore with npx playwright install chromium --force. See trap file-stripping.',1,'2026-08-26 17:01:06',NULL);
CREATE TABLE events (
    id          INTEGER PRIMARY KEY,
    ts          TEXT NOT NULL DEFAULT (datetime('now')),
    session     TEXT,
    kind        TEXT NOT NULL CHECK (kind IN
                  ('decision','error','milestone','removal','install')),
    summary     TEXT NOT NULL,
    detail      TEXT
);
INSERT INTO "events" VALUES(1,'2026-08-26 15:32:10','a9593032','milestone','Structured memory database created and hourly backup registered','SQLite 3.50.4 via Python. Dump-and-hash backup to private repo dancockrell/memory-db. Scheduled task ClaudeMemoryBackup, hourly.');
INSERT INTO "events" VALUES(2,'2026-08-26T22:52:38','quickgrade-session','milestone','QuickGrade: answer sheet redesign and a visual inspection rig','Added tools/look.js: it renders a page and reports truncated text, collisions, ink too light or thin to survive a photocopier, content escaping its page, and unreadably small type, with annotated and layer screenshots. It immediately found four real defects, including truncated correct answers and a PAGE label running under the first page bubble on every sheet the app had ever printed. Also: questions now print on the answer sheet beside their own bubbles; corner fiducials are registration brackets rather than solid squares, where the arm width is a robustness number and not a taste one (0.5 of the mark measured 0.71 fill against a 0.70 detector threshold and lost corners to noise, 0.58 measures 0.80); the test code is a ten-mark strip instead of thirty pre-filled bubbles; and pages after the first drop the repeated header.');
INSERT INTO "events" VALUES(3,'2026-08-26 15:53:34','dr-companion-session','milestone','Recorded dr-companion invisible dependencies after the Ruby removal','Verified Ruby 4.0.6 at C:\Ruby4Lich5\4.0.6 is present and the three Ruby test suites pass. Added ComfyUI, the FLUX.1-schnell checkpoint (licensing critical), the Genie 4 map XML, and the Node 24 requirement, none of which appear in package.json or any README.');
INSERT INTO "events" VALUES(4,'2026-08-26 15:56:40','a9593032','removal','FLUX.1-dev deleted (16.06 GB, non-commercial licence)','flux1-schnell-fp8 Apache-2.0 retained. dr-companion pins schnell in two files; swapping dev in would make its art pack legally unusable.');
INSERT INTO "events" VALUES(5,'2026-08-26 15:57:08',NULL,'milestone','world-aflame-godot: shipped Skirmish (Snap-inspired simultaneous-reveal ruleset), 1500 keyword-driven generated cards (500/faction), and witness-chain (github.com/dancockrell/witness-chain) -- a standalone dual-signature hash-chain ledger for tamper-evident match records, built for reuse across game projects, not just this one.',NULL);
INSERT INTO "events" VALUES(6,'2026-08-26 16:01:09','a9593032','decision','Co-located dependency warnings generated from the DB','mem export writes DEPENDENCIES.md into project dirs; mem guard writes WHAT-USES-THIS.md into the dependency''s own directory. Guard is the one that would have prevented the Ruby4Lich5 deletion.');
INSERT INTO "events" VALUES(7,'2026-08-26 16:02:25',NULL,'decision','The Raven''s narration was recovered from raven-itch-folder zips and committed: 368 mp3 plus a 368-cue WebVTT converted from the original timings.js with zero round-trip failures. The pack''s own AUDIO-NEEDED.md had claimed the audio was gone and unreconstructable; every part of that was false. It is now AUDIO-RECOVERED.md.',NULL);
INSERT INTO "events" VALUES(8,'2026-08-26 16:02:25',NULL,'milestone','magi-reader-engine: feature complete and green. 676 unit tests, 642 e2e across four engines. A book is runtime state rather than a compile-time import, the engine has its own fixture book, and a parity test carries the prototype''s inventory so nothing can be dropped or added without a written decision.',NULL);
INSERT INTO "events" VALUES(9,'2026-08-26 16:09:32','dr-companion-session','error','Nudity gate passed against an empty prompt file','tools/safety-test.mjs runs first in the chain so a regression fails the build before anything else. Pointed at {} it reported all 0 carry it / 0 checked / all passed / exit 0. Fixed in 21e6b06: every none-of-these-are-bad assertion now also asserts the set was not empty, in that suite and six more in the gateway suite.');
INSERT INTO "events" VALUES(10,'2026-08-26 16:12:15','a9593032','decision','guard and review now assert a non-empty denominator','Both reported clean and exit 0 against a wiped database - demonstrated, not reasoned. Now print what was checked and exit 1 when there is nothing to check.');
INSERT INTO "events" VALUES(11,'2026-08-26 16:21:59','a9593032','decision','CLAUDE.md reworked, not appended','Rule 1 rewritten to absorb three overlapping verification lessons into one section with a table of six instances. Header now explicitly invites every session to edit and merge rules, not only append. Numbering declared history, not hierarchy.');
INSERT INTO "events" VALUES(12,'2026-08-26 16:22:44',NULL,'decision','Named a failure class shared across three sessions on 2026-08-26: the check that reports success when it did not execute. Instances: a git audit comparing against origin/<local-branch-name> that does not exist; a test runner counting FAIL lines in output from a suite that crashed; an assertion carrying a term that was always zero; a regex strip that never matched; and the detector written to find them, which found nothing because it read no files. Recorded so the shape is recognisable rather than rediscovered.',NULL);
INSERT INTO "events" VALUES(13,'2026-08-26 16:24:49',NULL,'decision','Declined a peer request to rewrite C:\Users\Admin\.claude\CLAUDE.md. The peer reported that Dan had opened the file to all sessions; that may well be true, but a relayed authorisation is not an authorisation, and CLAUDE.md is the file that governs how every session behaves. Proposed rule text was surfaced to Dan directly instead.',NULL);
INSERT INTO "events" VALUES(14,'2026-08-26 16:26:32','a9593032','decision','Retracted a CLAUDE.md edit invitation sent to three peer sessions','Dan authorised me; I relayed it as authorisation for them. That is permission laundering. Two retractions sent; Magi Reader had already refused and escalated correctly.');
INSERT INTO "events" VALUES(15,'2026-08-26 16:38:39',NULL,'error','Wrote four checks for two dependency rows and every one of them was wrong in the same direction, each printing a plausible zero: a PowerShell wildcard path with -Filter (0 instead of 368); node not on PATH so a tool that never ran reported 0 plates; the wrong extension and directory (.png in public/audio when the files are .webp in public/magi-audio); and git -C failing on a path with an apostrophe, whose error piped into wc -l printed 0 dirty files. Zero is what a broken check says.',NULL);
INSERT INTO "events" VALUES(16,'2026-08-26 16:50:02',NULL,'error','mem review reported six live dependency locations as GONE','Path(loc).exists() was applied to URLs, prose, wildcards and relative paths alike. Fixed with classify_location plus test_classify.py: 10 cases, 2 of which assert real absence, so the suite cannot pass with a classifier that never reports gone. Reported by the Magi Reader session as one row.');
INSERT INTO "events" VALUES(17,'2026-08-26 16:50:02',NULL,'milestone','magi book media confirmed to exist in exactly one place','743 files, 27.5 MB, committed to dev/magi-reader whose remote is a hard 404. Verified against the GitHub tree API for all three magi repos: engine has 5 media under docs/, classroom-toolkit has 0, the-raven has its own 368 in pack/audio. Surfaced to Dan; publishing is his call.');
INSERT INTO "events" VALUES(18,'2026-08-27T00:01:06','quickgrade-session','decision','A suite that asserts nothing now fails the runner','tools/check.js printed "asserted nothing" beside a green line and counted the suite as passing. That is the same defect the runner exists to catch: an absent result and a negative result print identically, and the absent one looks like success. The count of checks is the fragile number, the one that goes to zero when the mechanism breaks, so it is the one to assert on. Demonstrated with a suite that exits 0 having run nothing: it now reads FAIL. Also added a substring filter, because a ten-minute suite is one a person checking a single thing will skip entirely.');
INSERT INTO "events" VALUES(19,'2026-08-26 17:14:51',NULL,'decision','Dan authorised editing CLAUDE.md directly on 27 Aug 2026 after I declined the same request relayed through a peer. Added to it: a fifth sub-rule under section 1 (zero is what a broken check says, from four broken checks in one sitting); four machine traps under section 10 (deleted remote reports in sync, PowerShell wildcard-dir with -Filter returns 0, node/gh not on PowerShell PATH, git -C fails on apostrophe paths); a cross-session rule under section 13 (a session cannot pass on permission it was given); and section 19, write the check not the claim.',NULL);
INSERT INTO "events" VALUES(20,'2026-08-26 17:20:21',NULL,'milestone','CLAUDE.md section 1 gained the false-positive rule','A check that always fires is as empty as one that never does. From mem review listing six live locations as GONE, plus the over-correction that demoted a real path. Verified with check-xrefs.py after the edit: 22 sections, 14 references, all resolving.');
INSERT INTO "events" VALUES(21,'2026-08-26 17:23:21',NULL,'decision','Corrected CLAUDE.md section 12 on 27 Aug 2026. It had said ''escapes and heredocs do not mix'' and that \b ''arrives as an actual backspace (0x08)''. Both wrong in ways that matter: the collapse is done by the Bash tool to the whole command string regardless of quoting, so a quoted heredoc is not the safe harbour the old wording implied, and the 0x08 is produced by the consuming language rather than the shell. Measured rather than reasoned. The same false mechanism appeared twice in the file and only one copy would have been fixed without looking for the second, which is that section''s own rule about copies.',NULL);
INSERT INTO "events" VALUES(22,'2026-08-26 18:01:47',NULL,'decision','Fixed the quality findings in all three Magi Reader books on 27 Aug 2026 rather than only reporting them. Position bias was mechanical so it got a tool; the length tell was writing so 67 distractors were rewritten by hand. Added answerCycle to quality.js because the obvious fix for position bias (round-robin) produces a perfect even spread and a visible cycle that scores 100%, which the existing check would have called clean. The test asserting Magi WAS beatable was inverted rather than deleted, as its own comment asked.',NULL);
INSERT INTO "events" VALUES(23,'2026-08-26 18:06:41',NULL,'error','snapshot.py''s first version decided whether to commit by comparing the copied files against their source. The dry run had already copied everything, so the --commit run found no difference and printed ''nothing changed, so nothing to commit'' against a repository with ZERO commits and ZERO tracked files. The skip condition was satisfiable by the commit having never happened, which is the exact failure class the repo was created to protect against. Fixed to ask git status --porcelain instead of the copy step. Caught only by checking rev-list --count afterwards rather than reading the reassuring message.',NULL);
INSERT INTO "events" VALUES(24,'2026-08-26 18:08:40',NULL,'error','advised a bare git init on .claude, which would have staged nine .key files','Corrected by the Magi Reader session before Dan acted on it. The fix is an allowlist copy into dev/claude-config, not a denylist .gitignore: a denylist fails by leaking whatever nobody thought of, an allowlist fails by missing a file.');
INSERT INTO "events" VALUES(25,'2026-08-26 18:13:14',NULL,'decision','Added a round-trip test to dev/claude-config on 27 Aug 2026: clone the repo and compare every restored file against its source in .claude. It found a real defect on its first run (the autocrlf rewrite) which four earlier checks had missed, because all of them asked whether the right things went IN and none asked whether they came back OUT unchanged. For a backup that is the only question that matters.',NULL);
INSERT INTO "events" VALUES(26,'2026-08-26 18:20:52',NULL,'error','My repo sweep flagged 10 of 23 repos under dev/ as at risk. Six were false: gf-art, ghost-front, longnight, profile-readme, raven-classroom and world-aflame all differ from their remote HEAD, but GitHub HAS their local HEAD -- the remotes are simply ahead. The bug was folding ''could not determine'' into ''at risk'': rev-list could not count because the remote object was never fetched locally, and I printed ''?'' then treated it as a risk. That is the tri-state failure another session named earlier tonight, in my own tool, hours later. The right question is not ''are local and remote equal'' but ''does the remote CONTAIN the local HEAD'', answered by gh api repos/OWNER/NAME/commits/<sha>.',NULL);
INSERT INTO "events" VALUES(27,'2026-08-26 18:23:45',NULL,'decision','hardened the gitleaks pre-commit template, left 23 existing repos alone','The old template failed open. New template falls back to PATH before refusing, and refuses loudly. Existing repos keep their copy: init.templateDir only applies at init/clone, and rewriting 23 hooks while five sessions are committing is a bigger risk than the latent one being fixed. Rollout is Dan''s call; the one-liner is in the report.');
INSERT INTO "events" VALUES(28,'2026-08-26 18:27:01',NULL,'decision','Swept the machine for hook bypasses on 27 Aug 2026: git aliases global and per-repo, core.hooksPath, HUSKY env, shell profiles, and 292 scripts and package.json files under dev/ and magi-app. Zero instances of --no-verify. Proved the matcher fires first by planting two canaries (a .sh and a package.json) and confirming 2 of 2 hits, so the zero is a real zero rather than an unproven grep.',NULL);
INSERT INTO "events" VALUES(29,'2026-08-26 18:37:37',NULL,'error','While testing the new magi-app pre-commit hook I put marker echoes at the top of it, staged a throwaway probe.txt, and committed to see which markers survived. The commit SUCCEEDED, because a file with no secret in it is supposed to pass, and my follow-up `git reset --soft HEAD` was a no-op that reset to the commit I had just made. A stray ''probe'' commit sat on master until I checked git log. Never pushed; undone with reset HEAD~1 and confirmed equal to origin/main again. The lesson is that a test which commits for real needs its undo written before the test runs, not after, and `reset --soft HEAD` is not an undo.',NULL);
INSERT INTO "events" VALUES(30,'2026-08-27 00:09:23',NULL,'decision','Pushed Magi Reader 0.8.0 to itch on 27 Aug 2026 at dancockrell/the-gift-of-the-magi:html. No cleanup of old versions was needed or possible: Dan had already cleared the account, so the project had zero channels and this push created the first one. From here, pushing to html replaces that channel''s build, which is the discard-the-old behaviour he asked for. The legacy single-file prototype was built (magi-reader-0.8.0-legacy.zip, 745 files) but NOT pushed, since only the default channel is what visitors play and the prototype''s durable home is the git tag.',NULL);
INSERT INTO "events" VALUES(31,'2026-08-27 00:18:28',NULL,'decision','Pushed both readers to itch on 27 Aug 2026: dancockrell/the-gift-of-the-magi:html at 0.8.0 (build #1919082) and dancockrell/the-raven-edgar-allen-poe:html at 1.0.0 (build #1919096). BOTH currently present as downloads rather than browser-playable, because itch only treats an html channel as playable when the project''s Kind of project is set to HTML, which is web-UI-only and butler cannot change. Flagged to Dan. Also flagged: the raven''s itch slug and page title spell it Edgar ALLEN Poe; the reader itself spells it correctly.',NULL);
CREATE TABLE facts (
    id          INTEGER PRIMARY KEY,
    category    TEXT NOT NULL CHECK (category IN
                  ('user','project','reference','feedback','trap','tool')),
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    confidence  TEXT DEFAULT 'verified' CHECK (confidence IN
                  ('verified','reported','inferred')),
    source      TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now')), check_cmd TEXT,
    UNIQUE (category, key)
);
INSERT INTO "facts" VALUES(1,'trap','vram-wmi','Win32_VideoController.AdapterRAM reports the RTX 4070 as 4 GB (32-bit overflow). Use nvidia-smi.','verified','2026-08-23','2026-08-26 15:29:46','2026-08-26 15:29:46',NULL);
INSERT INTO "facts" VALUES(2,'trap','crlf-scripts','Heredocs write LF; cmd.exe mis-parses LF-only scripts with misleading errors. Fix with sed then verify with cat -A.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46',NULL);
INSERT INTO "facts" VALUES(3,'trap','temp-wipe','Never clear TEMP wholesale on a running system. Broke a Chrome update mid-flight, removing chrome.exe while 268 files stayed intact.','verified','2026-08-26','2026-08-26 15:29:46','2026-08-26 15:29:46',NULL);
INSERT INTO "facts" VALUES(4,'trap','git-noreply','Commits must use the GitHub noreply email or pushes are rejected, and the error does not say so.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46',NULL);
INSERT INTO "facts" VALUES(5,'trap','exec-policy','LocalMachine execution policy is AllSigned, blocking npm.ps1. npm works in Git Bash and cmd.','verified','2026-08-24','2026-08-26 15:29:46','2026-08-26 15:29:46',NULL);
INSERT INTO "facts" VALUES(6,'tool','gpu','RTX 4070, 12012 MB VRAM. Models above ~12 GB spill to shared memory.','verified','2026-08-23','2026-08-26 15:29:46','2026-08-26 15:29:46',NULL);
INSERT INTO "facts" VALUES(7,'trap','file-stripping','Something on this machine strips large files out of untracked dependency trees, and not only in Downloads. 26 Aug 2026: between two runs of the same suite half an hour apart, Downloads/testgrader/tools/node_modules/playwright-core went from a working install to 733 KB with every .js bundle gone and only LICENSE files left, and icudtl.dat disappeared from AppData/Local/ms-playwright/chromium_headless_shell-1234, so Chrome launched and died with ''Invalid file descriptor to ICU data received'' while --version still worked. Git-tracked files were untouched. Recovery: remove node_modules entirely and reinstall (a plain npm install says ''up to date'' from the lockfile without checking file contents, so it does nothing), then npx playwright install chromium --force. Treat an inexplicable module-not-found, or a browser that starts and then dies, as this before suspecting code.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38',NULL);
INSERT INTO "facts" VALUES(8,'trap','python-none-on-path','There is no working ''python'' on PATH. python and python3 both resolve to the Windows Store aliases in AppData/Local/Microsoft/WindowsApps, which advertise the Store and exit without executing anything. ''py'' is not installed. The conda install at C:/Users/Admin/anaconda3/python.exe starts under a conda shell but NOT from a child process (it fails with ''Could not find platform independent libraries'') because it needs its own directories on PATH for its DLLs. The one that works from anything is C:/Users/Admin/AppData/Local/Programs/Python/Python313/python.exe, 3.13.15. Any script that shells out to Python must probe a candidate with -c print(1) rather than trust a name, or the fact that a file exists on disk.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38',NULL);
INSERT INTO "facts" VALUES(9,'trap','pip-broken','pip on the Python313 install is itself damaged: ''No module named pip._vendor.rich._emoji_codes''. python -m ensurepip --upgrade does not repair it, because ensurepip reads the recorded version, sees pip present and stops. Same family as the file-stripping trap. Consequence: no pip installs on that interpreter until it is repaired, so plan around it rather than through it. Reading a PDF, for instance, was done by rendering it with pdf.js inside headless Chromium instead of installing pypdf.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38',NULL);
INSERT INTO "facts" VALUES(11,'trap','crlf-breaks-anchors','Repos here are checked out with CRLF endings, so a patch script that matches a multi-line anchor joined with newline finds nothing, makes no change, and reports success. Detect the ending first and build anchors with it, or splice by line number. This wasted several rounds before it was noticed, because every symptom looked like a wrong anchor string.','verified','quickgrade-session','2026-08-26T22:52:38','2026-08-26T22:52:38',NULL);
INSERT INTO "facts" VALUES(12,'trap','cuda-dll-path','pip nvidia-* wheels put DLLs in site-packages/nvidia/*/bin. os.add_dll_directory is NOT enough - CTranslate2 resolves cuBLAS via its own LoadLibrary. Prepend those dirs to os.environ PATH before importing faster_whisper. Symptom: Library cublas64_12.dll is not found.','verified','2026-08-23','2026-08-26 15:53:01','2026-08-26 15:53:01',NULL);
INSERT INTO "facts" VALUES(13,'trap','uv-python-312','uv venv --python 3.12 fails with a spurious ''missing expected target directory'' error. Pass the interpreter path directly instead.','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01',NULL);
INSERT INTO "facts" VALUES(14,'trap','winget-fresh-terminal','winget-installed binaries do not resolve until a NEW terminal opens. They live under AppData/Local/Microsoft/WinGet/Packages/<Publisher.Name>_<hash>/','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01',NULL);
INSERT INTO "facts" VALUES(15,'trap','ollama-app-supervises','Killing ''ollama app'' kills the server - the desktop app supervises ''ollama serve'' and port 11434 goes with it.','verified','2026-08-24','2026-08-26 15:53:01','2026-08-26 15:53:01',NULL);
INSERT INTO "facts" VALUES(16,'trap','rust-not-on-path','Rust 1.98.0 is installed at %USERPROFILE%/.cargo but is NOT on PATH in Git Bash. Tauri builds need it.','verified','2026-08-26','2026-08-26 15:53:02','2026-08-26 15:53:02',NULL);
INSERT INTO "facts" VALUES(17,'trap','transcript-no-speaker','search_session_transcripts returns user messages, assistant messages and tool output undifferentiated. Never attribute a snippet without checking who produced it.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02',NULL);
INSERT INTO "facts" VALUES(18,'trap','verify-outcome-not-output','gh repo create --push prints the repo URL whether or not the push succeeded. Verify state via API, never stdout. Cost: 11 repos reported pushed while empty, 3 times.','verified','2026-08-24','2026-08-26 15:53:02','2026-08-26 15:53:02',NULL);
INSERT INTO "facts" VALUES(19,'feedback','publish-voice','Anything Dan publishes under his own name: no em dashes or middle-dot separators, no delve/leverage/robust/seamless, no reflexive three-item lists. His audience (educators) is the most AI-text-fatigued group in the workforce.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02',NULL);
INSERT INTO "facts" VALUES(20,'feedback','claim-standard','Only claim what survives an unannounced test. Dan''s own rule, applied to his languages and skills. Applies to READMEs, commit messages and status reports too.','verified','2026-08-25','2026-08-26 15:53:02','2026-08-26 15:53:02',NULL);
INSERT INTO "facts" VALUES(21,'trap','npm-test-fail-grep-is-unsound','Counting "^FAIL" lines in npm test output reports 0 failures when a suite CRASHES rather than fails. dr-companion without Ruby on PATH: exit code 1, 313 OK lines, 0 FAIL lines - 90 assertions never ran and the check said clean. Read the exit code. This was used repeatedly before it was caught.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34',NULL);
INSERT INTO "facts" VALUES(22,'trap','heredoc-escapes-arrive-mangled','An escape written through a shell heredoc does not survive. \b arrives as an actual backspace (0x08), \s as plain s. The regex still compiles and matches nothing, so it looks like empty data rather than a broken pattern. Hit three times in one session with the trap already documented. Use the file-edit tool for anything containing escapes and verify with charCodeAt.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34',NULL);
INSERT INTO "facts" VALUES(23,'trap','deleting-unused-data-is-an-invisible-bet','Deleting a derived artefact that nothing currently reads is a bet that no future feature needs it. The bet is invisible when made and silent when lost. The art daemon deleted each evaluation thumbnail after scoring it - obviously correct, small files, already consumed - and when the scoring scale turned out to be wrong, 172 renders could not be re-measured. Ask what would need this if the thing that produced it were wrong.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34',NULL);
INSERT INTO "facts" VALUES(24,'trap','old-data-under-a-new-meaning','Values stored under a key whose meaning later changes are the quietest bug available: nothing errors and every number looks plausible. Measures saved as "stdev" meant raw pixels; the next version read the same key as contrast-normalised. Clear stale values rather than converting them - a converted number carries the same false confidence and is harder to spot. Same shape as a schema change CREATE TABLE IF NOT EXISTS silently skips.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34',NULL);
INSERT INTO "facts" VALUES(25,'project','dr-companion-art-pack-size','17,750 room images at a mean 178 KB is about 3.0 GB, against a 72 MB repository. public/rooms is gitignored and needs a release-asset distribution path (issue #8). Creatures (773) and portraits (22) ARE committed at 53 MB because every card and character sheet needs them.','verified','dr-companion-session','2026-08-26 15:53:34','2026-08-26 15:53:34',NULL);
INSERT INTO "facts" VALUES(26,'trap','flux-dev-removed','FLUX.1-dev (non-commercial) was deleted from ComfyUI models on 2026-08-26. Only flux1-schnell-fp8 (Apache-2.0) remains, which is what dr-companion pins. Do not reinstall dev - it would make generated art packs legally unusable.','verified','2026-08-26','2026-08-26 15:56:40','2026-08-26 15:56:40',NULL);
INSERT INTO "facts" VALUES(27,'trap','fail-line-counting','Counting FAIL lines in test output is unsound. dr-companion without Ruby: exit code 1, 313 passing assertions, ZERO FAIL lines, 90 assertions never ran. Read the exit code, not the output. Generalises rule 1.','verified','dr-companion-session','2026-08-26 15:56:40','2026-08-26 15:56:40',NULL);
INSERT INTO "facts" VALUES(28,'feedback','colocate-warnings','A shared database helps a session that thinks to query it. A README in the directory reaches whoever is standing there deciding what to delete. Both are needed; the second is the one that catches an outsider. Put the warning where the mistake would happen.','verified','dr-companion-session','2026-08-26 15:56:40','2026-08-26 15:56:40',NULL);
INSERT INTO "facts" VALUES(29,'feedback','warning-placement','The warning goes where the DESTRUCTIVE ACTION happens - not where the dependency is declared, not where a careful reader would look. A project README reaches someone reading the project. It does not reach someone standing in C:\Ruby4Lich5 deciding if that folder is clutter. Use ''mem guard'' to write WHAT-USES-THIS.md into the dependency''s own directory.','verified','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09',NULL);
INSERT INTO "facts" VALUES(30,'trap','stale-warning-worse-than-none','A warning describing a situation that has changed is worse than no warning: it spends the reader''s attention and teaches them the file is stale. Regenerate co-located warnings from the DB rather than hand-maintaining them.','verified','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09',NULL);
INSERT INTO "facts" VALUES(31,'trap','burst-vs-recurring','visual-rig ''recurring'' flags a run of events sharing one timestamp as STILL GOING. 14 dr-companion warnings all stamped 22:51:49 were a single injection, not an ongoing fault. Events sharing one timestamp are a burst - needs a rule.','reported','dr-companion-session','2026-08-26 16:01:09','2026-08-26 16:01:09',NULL);
INSERT INTO "facts" VALUES(32,'trap','PYTHON_ON_PATH_IS_A_STUB','python.exe on PATH is the Windows Store alias at AppData\Local\Microsoft\WindowsApps and fails with ''the file cannot be accessed by the system''. The real interpreter is C:\Users\Admin\AppData\Local\Programs\Python\Python313\python.exe. There is no py launcher.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(33,'trap','POWERSHELL_APOSTROPHE_IN_LEGACY_PATH','The magi-app repo lives under a folder literally named ''Legacy builds and Assets...if you can''''t find something, try here''. The apostrophe in can''''t breaks every single-quoted PowerShell string and every inline node -e that embeds the path. Use a script file and pass the path as an argument, or Join-Path with a variable. This broke four separate commands in one session.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(34,'trap','NODE_INLINE_EVAL_MANGLES_REGEX','node -e through PowerShell mangles backticks, dollar signs and backslashes, so regex literals and template strings arrive corrupted. A .mjs file run by path is the only reliable route. Symptom: ''Unterminated regexp literal'' or a replacement that silently matches nothing.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(35,'trap','RAVEN_AUDIO_LIVES_IN_ZIPS','The Raven''s 368 narration mp3s and its word-level timings.js were only ever inside raven-itch-folder.zip / _2 / _4 / _6 beside the magi-app folder. They are now committed to dancockrell/the-raven-edgar-allan-poe-magi-reader under pack/audio and pack/cues. Before deleting any raven-itch-folder zip, confirm that repo still has 368 files in pack/audio.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(36,'trap','MAGI_MEDIA_IS_SPREAD_ACROSS_FOLDERS','No single folder holds a complete set of Magi''s art. magi-itch-ui has 29 of 54 plates, magi-itch-guide2-clean 20, magi-itch-improved 13. Only the union is whole, which is why tools/copy-assets.mjs now searches seven sources and takes the union instead of naming one folder.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(37,'trap','PLAYWRIGHT_ITCH_TEST_NEEDS_ITS_OWN_RUN','magi-app''s e2e/itch.spec.js stands up two extra HTTP servers and loads the built game in an iframe. Under four workers it times out even at 90s; alone it takes 12.6s. Tagged @serial, run by npm run e2e:serial, and verify:full runs it FIRST because running it after the parallel suite fails on a warm machine. Do not answer this by raising the timeout again; that was tried twice.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(38,'trap','MAGI_APP_IS_BACKED_UP','magi-app in the Legacy folder DOES have a remote: github.com/dancockrell/magi-reader-engine, branch master pushing to main, 44 commits, clean. A report that it has no remote and zero commits was wrong, probably from running git in the wrong directory. Verify with git config --get remote.origin.url before ''rescuing'' it.','verified',NULL,'2026-08-26 16:02:25','2026-08-26 16:02:25',NULL);
INSERT INTO "facts" VALUES(39,'feedback','generated-warnings-need-correct-source','Generating a warning file from a database is right - it cannot drift - but it only moves the accuracy problem to the row. Two of the dr-companion rows were wrong within an hour: one said the project ''works alongside'' Genie when it only reads its map files, and one said FLUX.1-dev was on this machine after it had been deleted. Fix the row, not the file. And treat a thin row as a bug, because the generated file can only be as specific as its source.','verified','dr-companion-session','2026-08-26 16:03:10','2026-08-26 16:03:10',NULL);
INSERT INTO "facts" VALUES(40,'trap','git-audit-branch-mismatch','My repo audit reported magi-app as having 0 commits and no remote. Wrong: it is dancockrell/magi-reader-engine with 44 commits, clean. The bug was mine - I computed unpushed as ''origin/$branch..HEAD'' using the LOCAL branch name. magi-app is master locally pushing to main, so origin/master does not exist and the check silently returned nothing. Compare against the remote''s actual default branch.','verified','2026-08-26','2026-08-26 16:05:55','2026-08-26 16:05:55',NULL);
INSERT INTO "facts" VALUES(41,'trap','silent-skip-hides-gaps','A skip counted as housekeeping hides real gaps. mem guard reported ''7 skipped (URLs and non-directories)'' while the FLUX licence dependency - the one with a legal consequence - had no warning file anywhere. Skips must be loud and itemised.','verified','dr-companion-session','2026-08-26 16:05:55','2026-08-26 16:05:55',NULL);
INSERT INTO "facts" VALUES(42,'trap','generated-from-bad-row','Generating a warning from a database moves the accuracy problem to the row, it does not remove it. The file cannot drift from the row; the row can still be wrong or thin. A one-line ''why'' produces a warning nobody stops for - same defect as an empty warning, harder to see.','verified','dr-companion-session','2026-08-26 16:05:55','2026-08-26 16:05:55',NULL);
INSERT INTO "facts" VALUES(43,'trap','legacy-folder-apostrophe','The Legacy folder name contains an apostrophe ("...if you can''t find something..."). It breaks every single-quoted PowerShell string and every inline node -e touching that path. Use double quotes or a variable.','verified','magi-reader-session','2026-08-26 16:05:55','2026-08-26 16:05:55',NULL);
INSERT INTO "facts" VALUES(45,'trap','negative-result-vs-absent-result','The commonest bug across three sessions in one day: a check reports success because it never ran. A negative result and an absent result are indistinguishable unless you make them different. Four instances, all silent: counting FAIL lines in a suite that crashed (exit 1, zero FAIL lines, 90 assertions never run); asserting none of these prompts are missing the clause against an EMPTY file (all 0 carry it, passed - and that is the gate that runs first to stop a nudity regression); a dependency guard reporting 7 skipped where the skips WERE the unprotected paths; a git check against origin/master in a repo pushing to main. Fix: prove the work happened. Read exit codes. Assert a floor on how many things were checked, set well below the real count. Print the count. Make skips loud and non-zero-exit.','verified','dr-companion-session','2026-08-26 16:09:32','2026-08-26 16:09:32',NULL);
INSERT INTO "facts" VALUES(46,'trap','negative-vs-absent-result','A negative result and an absent result print identically unless you make them different, and the absent one looks like success. Four instances in one session: safety-test.mjs passed against an empty prompt file; a FAIL-line count reported clean on a crashed suite; mem guard reported ''0 written'' against a wiped dependencies table; a git audit reported ''no remote'' when origin/$branch did not exist. Fix: assert the denominator is non-empty and print what was checked.','verified','dr-companion-session','2026-08-26 16:12:15','2026-08-26 16:12:15',NULL);
INSERT INTO "facts" VALUES(47,'feedback','denominator-must-be-the-fragile-thing','Count the check against the thing that goes to zero when the mechanism fails, not the thing that stays constant. ''No humanoid is undressed'' is true and meaningless if the humanoid detector classified nothing. Denominator = humanoids found, not creatures total.','verified','dr-companion-session','2026-08-26 16:12:15','2026-08-26 16:12:15',NULL);
INSERT INTO "facts" VALUES(48,'feedback','rules-recognise-they-do-not-prevent','Writing a rule down does not create the reflex. In one session I wrote ''verify the outcome not the output'' then broke it twice more; DR Companion wrote ''a stale warning is worse than none'' then left one for an hour. What actually caught both was another session inspecting the artefact. Rules help recognise a failure that is already in front of you. Cross-checking is what prevents it.','verified','dr-companion-session','2026-08-26 16:12:15','2026-08-26 16:12:15',NULL);
INSERT INTO "facts" VALUES(49,'reference','witness-chain-renamed','witness-chain was renamed to project-42-blockchain. Repo: dancockrell/project-42-blockchain. Any earlier reference to witness-chain means this.','verified','downloads-f5','2026-08-26 16:17:49','2026-08-26 16:17:49',NULL);
INSERT INTO "facts" VALUES(50,'trap','dual-signature-collusion','Dual-signature verification does not prevent collusion. Two cooperating signers can co-sign each other''s records indefinitely and dominate aggregate statistics (win-rate mining) without ever failing verification. Any consumer aggregating across a chain needs a DISTINCT-COSIGNER count, not a signature count. Raised against project-42-blockchain issue #1 by the World Aflame session.','verified','downloads-f5','2026-08-26 16:17:49','2026-08-26 16:17:49',NULL);
INSERT INTO "facts" VALUES(51,'trap','pipe-discards-exit-code','A shell pipeline reports the exit status of its LAST command. So `cmd 2>&1 | tail -1 || fallback` never runs the fallback, because tail always succeeds. Every git push in one dr-companion session used that pattern and the rebase fallback was dead code across 22 commits. It cost nothing only because the real check was comparing local and origin SHAs afterwards. Redirect to a file and test $?, or set pipefail. Two sessions hit this independently on 26 Aug 2026.','verified','dr-companion-session','2026-08-26 16:18:08','2026-08-26 16:18:08',NULL);
INSERT INTO "facts" VALUES(52,'trap','generated-file-not-regenerated','Generating a doc from a database removes drift only while something re-runs the generator. dr-companion DEPENDENCIES.md carried a claim that a model was on this machine for an hour after the database row had been corrected and the model deleted. The row was right; nothing had re-run export. Consider running the generator on any write to the source table, or flagging a generated file older than the row it came from.','verified','dr-companion-session','2026-08-26 16:18:08','2026-08-26 16:18:08',NULL);
INSERT INTO "facts" VALUES(53,'trap','python-backslash-U','Windows paths in Python source break on \U (C:\Users) and \x etc. Use r''...'' raw strings or forward slashes. Hit this twice in one session INCLUDING while writing the note about it.','verified','2026-08-26','2026-08-26 16:21:59','2026-08-26 16:21:59',NULL);
INSERT INTO "facts" VALUES(54,'trap','pipe-eats-exit-status','Never read $? after a pipe - it reports the LAST command''s status. ''cmd | tail'' always succeeds. Killed a git push retry fallback for 22 commits (DR Companion) and nearly made me file a working fix as broken.','verified','dr-companion-session','2026-08-26 16:21:59','2026-08-26 16:21:59',NULL);
INSERT INTO "facts" VALUES(55,'feedback','generate-then-nothing-reruns','Generating a file from a database does not help if nothing re-runs the generator. A file cannot drift while being written and drifts for as long as it is not. mem review now flags generated files older than their rows; export/guard touch mtime on no-op so the flag can actually clear.','verified','dr-companion-session','2026-08-26 16:21:59','2026-08-26 16:21:59',NULL);
INSERT INTO "facts" VALUES(56,'trap','VACUOUS_SWEEP_IN_TESTS','The test-suite form of ''a check that reports success without running'': a test walks a population, collects offenders, asserts the list is empty. That passes when nothing is wrong AND when nothing was examined. magi-reader-engine has tools/vacuous-sweeps.mjs to find them (40 sweeps, 29 with no population check, most benign). The fix is one line: assert the population was non-empty before asserting the offenders list is. Real instances found: plates over zero plates, answers over zero questions, translations over zero words, and an alignment sweep that ''continue''d past every clip when the cue file failed to load.','verified',NULL,'2026-08-26 16:22:44','2026-08-26 16:22:44',NULL);
INSERT INTO "facts" VALUES(57,'trap','DETECTOR_FOUND_ITSELF','The vacuous-sweep detector''s first version reported ''0 sweeps, 0 unguarded'' having found no test files at all: its parser started scanning inside a string literal and never terminated. A clean bill of health from a tool that examined nothing. Any auditing tool must print its own population count and exit non-zero when that count is zero, or it will one day report success for the wrong reason.','verified',NULL,'2026-08-26 16:22:44','2026-08-26 16:22:44',NULL);
INSERT INTO "facts" VALUES(60,'trap','peer-cannot-authorise-claude-md','Relayed permission is not permission. A session told three others that Dan had opened C:\Users\Admin\.claude\CLAUDE.md to all sessions. Its account was accurate and it was acting in good faith, and it still does not work: from the receiving side that message is indistinguishable from one that invented the authorisation, and the file governs how every session behaves. Applies to CLAUDE.md, permission settings and config. Decline, do the parts needing no escalation, and put the proposed change in front of Dan. RESOLVED 27 Aug 2026: Dan authorised it directly, in his own words, so the file IS editable by any session. The rule about relayed authorisation stands unchanged; only this instance is settled.','verified',NULL,'2026-08-26 16:26:32','2026-08-26 17:14:51',NULL);
INSERT INTO "facts" VALUES(61,'feedback','write-the-check-not-the-claim','When documenting the state of anything on disk, record the COMMAND that establishes it, not the answer that command gave once. A claim about what exists rots the moment the world moves and stays equally authoritative; its reader cannot re-derive it. ''The audio does not exist and cannot be reconstructed'' was unfalsifiable and wrong. ''Look in raven-itch-folder*.zip for raven-audio/'' is a 30-second check that stays true. AUDIO-NEEDED.md worked only because it was scary, not because it was informative.','verified','magi-reader-session','2026-08-26 16:26:32','2026-08-26 16:26:32',NULL);
INSERT INTO "facts" VALUES(62,'trap','PS_WILDCARD_PATH_WITH_FILTER_RETURNS_ZERO','PowerShell: Get-ChildItem on a path whose DIRECTORY portion contains a wildcard, combined with -Filter or -Include, silently returns 0. No error, and -ErrorAction Stop raises nothing. Get-ChildItem C:\Users\Admin\dev\the-raven-*\pack\audio -Filter *.mp3 returned 0 where the literal path returned 368; the wildcard form yields the directory itself as a single item, which then fails the filter. Resolve-Path on the same pattern resolves correctly, so the path is not the problem. Fix: put the wildcard in the LEAF, as "...\pack\audio\*.mp3", which returns 368. This matters because the zero reads as an honest absence of files.','verified',NULL,'2026-08-26 16:38:39','2026-08-26 16:38:39',NULL);
INSERT INTO "facts" VALUES(63,'trap','warning-list-of-false-positives','A warning list where every entry is a false positive is worse than no list. mem review reported six dependency locations as GONE; all six were live. Rows are only comparable if the check can distinguish ''absent'' from ''I could not check this''. Report the second honestly rather than folding it into the first.','verified','found by Magi Reader session, one row; six on inspection','2026-08-26 16:49:42','2026-08-26 16:49:42',NULL);
INSERT INTO "facts" VALUES(64,'trap','github-404-means-deleted-not-renamed','GitHub 301-redirects a renamed repository, so an old URL keeps working. A hard 404 from gh api repos/OWNER/NAME therefore means the repo was DELETED, not renamed. Use this to tell the two apart before assuming content moved to a similarly-named repo.','verified','dev/magi-reader remote 404 while magi-reader-engine exists','2026-08-26 16:49:43','2026-08-26 16:49:43',NULL);
INSERT INTO "facts" VALUES(65,'trap','guess-last-look-first','Order heuristics after facts. classify_location used a '' and '' substring to detect prose, which matched a real directory named ''Legacy builds and Assets...'' and demoted a checkable path to unchecked. Ask the filesystem first; apply guesswork only to strings that already failed to resolve.','verified','self-inflicted while fixing warning-list-of-false-positives','2026-08-26 16:49:43','2026-08-26 16:49:43',NULL);
INSERT INTO "facts" VALUES(66,'project','magi-media-single-copy','The magi book media (224 art + 519 audio = 743 files, 27.5 MB) is committed only to C:\Users\Admin\dev\magi-reader, whose GitHub remote dancockrell/magi-reader was DELETED (hard 404). magi-reader-engine holds 5 media files, all under docs/; magi-reader-classroom-toolkit holds 0. That working tree also has 94 uncommitted files. One disk, no remote. Dan''s call whether to publish.','verified','gh api git/trees recursive on all three repos, 2026-08-26','2026-08-26 16:49:43','2026-08-26 16:49:43',NULL);
INSERT INTO "facts" VALUES(67,'trap','dead-remote-reports-in-sync','A git repo whose GitHub remote was DELETED reports itself as fully pushed, because every local answer comes from the cached remote-tracking ref and nothing contacts the server. Demonstrated in C:\Users\Admin\dev\magi-reader on 26 Aug 2026, whose remote 404s: rev-list --count origin/main..HEAD says 0; rev-parse origin/main resolves; branch -vv prints [origin/main] as if tracking is healthy; and status -sb prints ''## main...origin/main'' with no ahead/behind marker, which is exactly what a synced repo prints. The commands that DO fail are git ls-remote --exit-code origin and git fetch --dry-run origin, both exit 128. So never read an unpushed count on its own: ask ls-remote first, and treat the count as meaningless if it fails. This is how 743 files read as backed up while existing on one disk. See [[github-404-means-deleted-not-renamed]] for telling deletion from a rename: GitHub 301-redirects a renamed repo forever, so a hard 404 means deleted.','verified',NULL,'2026-08-26 16:51:35','2026-08-26 16:51:35',NULL);
INSERT INTO "facts" VALUES(68,'trap','denominator-wider-than-the-claim','Counting evidence over a population broader than the claim makes an unbacked thing look backed up. Caught in my own verify-media.sh before it shipped: it summed ''.mp3'' across all three magi-reader repos to answer ''is The Gift of the Magi backed up'', so The Raven''s 368 narration files counted toward Magi''s total and it printed ''368 on GitHub'' for a book with zero files on GitHub. The fix is to partition by source and count by PATH, not by extension: grep for public/art and public/magi-audio specifically. Same shape as the four-checks-four-wrong list from the same hour. Ask what number goes to zero when the specific claim is false, and count that. Sibling of the rule that a check must assert its own population; this is the case where the population is real but belongs to something else.','verified',NULL,'2026-08-26 16:51:35','2026-08-26 16:51:35',NULL);
INSERT INTO "facts" VALUES(69,'reference','witness-chain-godot-ledger','Reusable dual-signature tamper-evident event ledger for Godot 4, MIT, at github.com/dancockrell/project-42-blockchain. Drop witness_chain/ into any Godot 4 project. No server, no cryptocurrency, no proof-of-work; two independent RSA signatures per record via Godot''s Crypto class, hash-linked as a DAG so concurrent branches merge without arbitration. Transport-agnostic: no networking code included. Built by the World Aflame session; world-aflame-godot uses it for replay-verified Elo. Verified on the remote 2026-08-27: 19 blobs, 4 commits, MIT, README present.','verified','gh api git/trees recursive, not the announcement','2026-08-26 17:13:45','2026-08-26 17:13:45',NULL);
INSERT INTO "facts" VALUES(70,'tool','claude-md-xref-checker','C:/Users/Admin/.claude/check-xrefs.py resolves every ''section N (hint)'' and ''rule N'' pointer in CLAUDE.md against the real headings and fails when a hint names a different rule. Built by the Magi Reader session; extended by the memory-db session to cover ''rule N'' and both letter cases, which doubled coverage from 7 references to 14. Its own proof is test-xrefs.py: 7 cases, 5 requiring a non-zero exit, run against temp copies so the live file is never mutated. Run both after editing CLAUDE.md.','verified','ran both; demonstrated failure in all five directions','2026-08-26 17:14:51','2026-08-26 17:20:21',NULL);
INSERT INTO "facts" VALUES(71,'tool','visual-rig-sees-top-layer-elements','REASONED, NOT OBSERVED. visual-rig should capture <dialog> and [popover] content, because it grabs the composited desktop framebuffer via mss: no DOM, no render tree, no accessibility API in the path, and a browser paints top-layer elements into its own window surface before that surface reaches the compositor. Same argument covers native menus, tooltips and OS overlays, which DOM-based tools cannot reach. The author''s empirical test was INVALID (the probe page was not focused, so the capture recorded a different window, and even ordinary page text came back missing) and they reported that rather than the conclusion. The real limitation is different and confirmed: the rig only sees what composites to a display, so an app rendering in a pane that never composites is invisible to it regardless. That is issue #9. TO VERIFY: open the reader with a dialog showing and in front, then visual-rig clip --window "<title>" -l "dialog open" and visual-rig ask "<string only the dialog shows>" --annotate.','inferred',NULL,'2026-08-26 17:20:09','2026-08-26 17:20:09',NULL);
INSERT INTO "facts" VALUES(73,'trap','ls-remote-before-counting-unpushed','Never read an unpushed-commit count without first asking whether the remote still exists. ''git rev-list --count origin/main..HEAD'' answers from the cached remote-tracking ref, so a DELETED remote reports a cheerful 0 and every other local signal agrees with it: rev-parse origin/main resolves, branch -vv prints [origin/main], status -sb shows no divergence marker. Only ls-remote and fetch --dry-run fail, with exit 128. Found when dev/magi-reader reported 0 unpushed while holding the only copy of 743 media files.','verified','verified on dev/magi-reader 2026-08-27','2026-08-26 17:21:12','2026-08-26 17:22:52','git -C C:/Users/Admin/dev/magi-reader ls-remote --exit-code origin');
INSERT INTO "facts" VALUES(74,'trap','bash-tool-eats-one-backslash','SHARPENED 27 Aug 2026, superseding bash-tool-heredoc-eats-one-backslash and the backslash half of heredoc-backslash, both of which named the wrong culprit. It is NOT heredoc-specific and quoting does not protect you: the Bash tool halves every backslash run in the command string before bash parses it. Measured with od -c: ''A\\B'' in SINGLE QUOTES arrives as ''A\B'', and bash''s own argv confirms it received the collapsed form, though POSIX says single quotes are literal. Inside <<''EOF'' likewise, where POSIX guarantees no processing at all. Single backslashes survive; runs are halved. Type 2N to get N. SECOND HALF: the 0x08 usually blamed on the shell comes from the LANGUAGE. Writing a doubled-backslash-b into a .js file leaves a single-backslash-b on disk, and JavaScript reads that as a backspace (charCodeAt(0) === 8, length 1), so both spellings produce byte-identical files. The distinction is gone before the language sees it, which is why the regex compiles and matches nothing instead of erroring. REMEDY: use Write/Edit for any file containing a backslash, or drop the escapes entirely (forward slashes work in Windows paths in Python, JS and Git Bash). Verify with od -c or charCodeAt, never by eye. See also [[bash-tool-truncates-long-heredocs]] and [[python-backslash-U]].','verified','measured 27 Aug 2026 by the magi-reader session with od -c and bash argv','2026-08-26 17:23:21','2026-08-26 17:24:57','printf ''%s'' ''A\\B'' | od -c    -- output ''A \ B'' means the trap is LIVE (one backslash survived of two, inside single quotes, where POSIX says both are literal). Output ''A \ \ B'' means the tool no longer collapses and this row is stale.');
INSERT INTO "facts" VALUES(75,'project','claude-config-unversioned','C:/Users/Admin/.claude is not a git repository and must not become one (see trap/claude-dir-holds-credentials). Hand-written substance is now snapshotted by allowlist into C:/Users/Admin/dev/claude-config: 41 files, CLAUDE.md + the two xref checkers + 32 memory markdown files, zero credential-shaped files tracked, verified clean by gitleaks AND an independent shape scan with a canary proving the scan fires. Built by the Magi Reader session. STILL HAS NO REMOTE - it holds Dan''s personal working notes, so pushing it is his call and private if anything.','verified','gitleaks 0 leaks over 41 files; shape scan 0 hits; canary detected','2026-08-26 17:23:49','2026-08-26 18:08:40','git -C C:/Users/Admin/dev/claude-config ls-files | grep -c ''\.key$''   # expect 0');
INSERT INTO "facts" VALUES(76,'trap','bash-tool-truncates-long-heredocs','Long heredocs through the Bash tool are truncated before their terminator. It surfaces as ''unexpected EOF while looking for matching'' and then silently runs NOTHING in the entire command, including any earlier commands on the same line, which is the dangerous part: a multi-step command reports failure for the last step while none of the earlier steps ran either. Write files in chunks under about 120 lines, or use the Write tool, which has no such limit. Separate failure mode from [[bash-tool-eats-one-backslash]]; both were filed together as ''heredoc-backslash'' and only the backslash half was superseded. Observed by the quickgrade session 26 Aug 2026; carried forward without re-measurement.','reported','quickgrade-session, via heredoc-backslash before consolidation','2026-08-26 17:24:57','2026-08-26 17:24:57',NULL);
INSERT INTO "facts" VALUES(77,'trap','genie-plugin-sees-server-text-only','The Genie CompanionBridge plugin (IPlugin.ParseText) receives GAME text only. Genie client-side output never reaches it: #echo, #config, #highlight, #reload and script output all come back silent on 127.0.0.1:7416. Consequence: every # command sent through tools/genie.mjs is fire-and-forget and success is indistinguishable from failure. Verify a Genie config change by reading the .cfg file back, never by sending #reload and moving on. The check needs Genie running with the plugin loaded; it prints the probe line and nothing else, and if the probe string ever comes BACK the trap is fixed.','verified',NULL,'2026-08-26 17:49:24','2026-08-26 17:49:54','cd /c/Users/Admin/dev/dr-companion && node tools/genie.mjs send "#echo ZQ-PROBE-7731" 4 | grep ZQ-PROBE-7731');
INSERT INTO "facts" VALUES(78,'trap','genie-autolog-off-means-no-logs','C:\Genie4\Config\settings.cfg has #config {autolog} {False} on a fresh install, so C:\Genie4\Logs is EMPTY. Zero log files reads as "no errors were logged" when it actually means nothing was ever written. Check the autolog setting before concluding anything from an empty Logs directory.','verified',NULL,'2026-08-26 17:49:24','2026-08-26 17:49:54','grep -i autolog /c/Genie4/Config/settings.cfg');
INSERT INTO "facts" VALUES(79,'trap','visual-rig-scene-activity-is-machine-wide','The "what the agent was doing" block in visual-rig scene output is machine-wide, not the focused session. With several Claude sessions running it interleaves all of their tool calls and carries NO field naming which session ran each one. Reading it as one session log led to messaging a peer to stop driving a game client it had never touched. Adjacency in a shared log is not attribution. The check greps a real scene for a session/agent identifier column: it finds none, which is the point.','verified',NULL,'2026-08-26 17:49:24','2026-08-26 17:49:54','visual-rig scene $(visual-rig clips --json | head -1) | sed -n "/what the agent was doing/,/^$/p" | grep -iE "session|agent id|pid" || echo "no actor field - trap still stands"');
INSERT INTO "facts" VALUES(80,'trap','gemstone-wording-in-dragonrealms-configs','GemStone IV and DragonRealms are different games from the same company (Simutronics). Lich was built by the community for one and ported to the other, so a single toolchain and a single config culture span both, and the other game vocabulary leaks into DragonRealms configs where it fires on nothing. Seen TWICE in one file, so treat it as the default suspicion rather than a one-off: (1) the mindstate ladder - GemStone clear/muddled/numbed/saturated vs DragonRealms clear/dabbling/perusing/.../mind lock; (2) wound severity - a bare "severe" was the only one of DragonRealms thirteen levels present. THE FIX IS AN INSTRUMENT, NOT CARE: Lich must parse this text to work, so Lich holds the authoritative lists, and the DIRECTORY says which game. lib/dragonrealms/ is DragonRealms (drinfomon/drvariables.rb DR_LEARNING_RATES, commons/common-healing-data.rb WOUND_SEVERITY, LODGED_SEVERITY, PARASITES_REGEX, and regex constants whose comments carry worked examples of the real game lines). lib/constants.rb is the other game. Diff any DragonRealms word list BOTH ways against the lib/dragonrealms table before trusting it.','verified',NULL,'2026-08-26 17:58:20','2026-08-26 23:54:09','cd /c/Users/Admin/dev/dr-genie-settings && node validate.mjs');
INSERT INTO "facts" VALUES(81,'tool','magi-book-quality-tools','magi-reader-engine has a second gate beside validate.js: src/lib/book/quality.js asks whether a book can be BEATEN, not whether it parses. Tools around it: quality-report.mjs (npm run book:quality) scores every book worst-first; debias.mjs permutes options to even out answer position without touching text; verify-debias.mjs proves the permutation kept every answer''s exact string; length-tell.mjs shows per-question how much a distractor needs to stop the answer being longest; patch-options.mjs applies option rewrites but refuses any edit whose expected text has moved; show-questions.mjs prints options with lengths. All three books scored 100 on 27 Aug 2026 (were 76, 84, 58). The gate still scores a deliberately wrecked book 0, verified.','verified',NULL,'2026-08-26 18:01:46','2026-08-26 18:01:46','cd magi-app && npm run book:quality   -- expect three books, all score 100');
INSERT INTO "facts" VALUES(82,'trap','magi-engine-pushes-master-to-main','magi-reader-engine''s local branch is master and its remote branch is main, so a bare ''git push'' is rejected with a message about branch.autoSetupMerge that does not say the branch names differ. Use: git push origin master:main. Then confirm by comparing git rev-parse HEAD against git ls-remote origin main, because the rejection is easy to read as success.','verified',NULL,'2026-08-26 18:01:47','2026-08-26 18:01:47','git -C <magi-app> rev-parse HEAD  and  git ls-remote origin main | cut -f1  -- equal means landed');
INSERT INTO "facts" VALUES(83,'trap','magi-itch-serial-test-flakes-under-load','e2e/itch.spec.js ''loads and reads inside a cross-origin iframe'' (@serial) has a 90s timeout and normally runs in about 750ms. Under the sustained load of npm run verify:full with several Claude sessions active it timed out twice at 90s, failing the husky pre-push hook. Confirmed NOT a regression: it passed three times standalone (753/756/719ms) including against a freshly built dist, then passed inside verify:full on the third push attempt. If it fails at push time, re-run npm run e2e:serial before believing it; do not reach for --no-verify.','verified',NULL,'2026-08-26 18:01:47','2026-08-26 18:01:47','cd magi-app && npm run e2e:serial   -- expect 5 passed in about 12s');
INSERT INTO "facts" VALUES(84,'trap','claude-dir-holds-session-keys','C:\Users\Admin\.claude\sessions\ contains *.key files (nine on 27 Aug 2026), so NEVER run git init plus git add -A in that directory: it commits credentials. It is also 333 MB, 331 MB of which is session transcripts under projects/. The hand-written part is about 150 KB. dev/claude-config versions that part by ALLOWLIST rather than gitignore, because a denylist protects you until someone adds a file nobody thought of, while an allowlist fails by missing something instead of by leaking it.','verified',NULL,'2026-08-26 18:06:41','2026-08-26 18:06:41','ls C:/Users/Admin/.claude/sessions/*.key | wc -l   -- nonzero means the hazard is live');
INSERT INTO "facts" VALUES(85,'trap','claude-dir-holds-credentials','C:/Users/Admin/.claude must NEVER be made a git repository directly. .claude/sessions/ holds nine *.key files, and the directory is 334 MB of which 331 MB is session transcripts under projects/. A git init there is one ''git add -A'' from committing credentials. .gitignore is the wrong instrument because a denylist fails by leaking whatever nobody thought of. Copy by ALLOWLIST into dev/claude-config instead: CLAUDE.md, settings.json, the xref checkers, projects/*/memory/*.md. An allowlist fails by missing a file, which is the safe direction.','verified','verified 2026-08-27; I had advised the naive git init and was wrong','2026-08-26 18:08:40','2026-08-26 18:08:40','find C:/Users/Admin/.claude -name ''*.key'' | wc -l   # expect 9, not 0');
INSERT INTO "facts" VALUES(86,'trap','autocrlf-silently-rewrites-a-backup','core.autocrlf is TRUE globally on this machine, so git stores LF and restores CRLF. For a repo whose purpose is fidelity that is corruption: dev/claude-config restored 32 of 33 memory notes with different bytes than the originals, because those notes are LF. CLAUDE.md is already CRLF, so it round-tripped perfectly and made the backup look sound -- the file most likely to be checked was the one file that could not reveal the bug. Fix: a .gitattributes containing ''* -text'' so nothing is translated, then re-add every file so the stored blobs are raw. Proved in an isolated repo: without .gitattributes an LF file DIFFERS after clone while a CRLF file is identical; with ''* -text'' both are identical. GENERAL FORM: a backup nobody has restored from is not a backup, and comparing only the file you happen to open can confirm the wrong thing.','verified',NULL,'2026-08-26 18:13:14','2026-08-26 18:13:14','cd C:/Users/Admin/dev/claude-config && python test_snapshot.py   -- the round-trip case clones and compares every file');
INSERT INTO "facts" VALUES(87,'trap','backup-never-restored-is-not-a-backup','Every check on a new backup asks whether something bad got IN. The only question that matters is whether what got in comes back OUT unchanged. dev/claude-config passed five separate audits (gitleaks, two shape scans, two filename audits) and still restored 32 of 33 memory notes with different bytes: core.autocrlf=true globally, git stored LF and restored CRLF. Worse, CLAUDE.md is one of only 3 CRLF files among 37, so the single file anyone would spot-check was incapable of revealing the defect. Fix is ''* -text'' in .gitattributes plus a re-add. Round-trip means clone to a FRESH directory and compare bytes; cloning at HEAD~1 inside an existing checkout does not re-normalise and shows a false pass.','verified','clone-and-compare, 37/37 identical after fix; found by Magi Reader','2026-08-26 18:15:52','2026-08-26 18:15:52','git clone -q C:/Users/Admin/dev/claude-config /tmp/rt && diff -r --brief /tmp/rt C:/Users/Admin/.claude');
INSERT INTO "facts" VALUES(88,'project','local-only-repos-sweep','Sweep of every repo under dev/ on 2026-08-27 asking ''ls-remote first, then count''. Three lack an off-machine copy: magi-reader (remote DELETED, 743 media files, 27.5 MB), claude-config (no remote by design, awaiting Dan), sirindhorn-m1-test (no remote, 10 commits, 41 files, 36 MB, ACTIVELY committed to 14 minutes before the sweep), world-aflame-unity (no remote, 1 commit, 20 files, 278 KB, the C# port of 150 card effects, superseded by world-aflame-godot). Everything else has a live remote and ahead=0. The ''dirty'' counts in gf-art (70), longnight (11) and others are pending DELETIONS whose content is safe in pushed history, not unbacked-up work.','verified','ls-remote --exit-code per repo, not rev-list','2026-08-26 18:15:52','2026-08-26 18:15:52','cd C:/Users/Admin/dev && for d in */; do git -C $d ls-remote --exit-code origin >/dev/null 2>&1 || echo $d; done');
INSERT INTO "facts" VALUES(89,'trap','gitleaks-hook-passes-when-binary-missing','The pre-commit hook in these repos begins: GITLEAKS=<winget path>; [ -x "$GITLEAKS" ] || exit 0. If that binary is ever moved or removed -- a winget update relocating the Packages folder, or a cleanup pass -- EVERY commit then passes the secret scan silently, with no message and exit 0. A security gate that reports success by not running. Verified 27 Aug 2026: the binary is present (gitleaks 8.30.1) so the gate is live TODAY, but the failure mode is one uninstall away and would be invisible. Fix is one line: make the missing-binary branch print and exit 1 instead of exit 0, so it fails closed. That is Dan''s call because it would block commits until the path is repaired.','verified',NULL,'2026-08-26 18:20:52','2026-08-26 18:20:52','ls -x "C:/Users/Admin/AppData/Local/Microsoft/WinGet/Packages/Gitleaks.Gitleaks_Microsoft.Winget.Source_8wekyb3d8bbwe/gitleaks.exe"  -- missing means the hook is silently passing everything');
INSERT INTO "facts" VALUES(90,'tool','gitleaks-actually-fires','MEASURED 27 Aug 2026, because two sessions had been quoting ''no leaks found'' without either having seen it find anything. It works. Blocked: a realistic ghp_ PAT, a Slack xoxb token, an sk-proj OpenAI key, a full-length RSA private key, and a non-example AWS key pair. Allowed through: ghp_ followed by 36 identical characters (low entropy, correctly ignored), AWS''s own PUBLISHED example keys AKIAIOSFODNN7EXAMPLE and wJalrXUtnFEMI... (deliberately allowlisted), and a 20-character truncated private key body. All four passes were weak canaries, not defects. RESIDUAL CAVEAT, which is CLAUDE.md section 7 demonstrated fresh: a file literally named creds.txt containing a low-entropy token committed clean, so gitleaks is a vendor-pattern-and-entropy matcher and still not a substitute for checking by filename and shape.','verified',NULL,'2026-08-26 18:20:52','2026-08-26 18:20:52','see gltest.sh method: commit a realistic ghp_ token in a scratch repo carrying the hook; it must be blocked');
INSERT INTO "facts" VALUES(91,'trap','gitleaks-hook-failed-open','The global pre-commit hook ended its lookup with ''[ -x $GITLEAKS ] || exit 0'', so if the winget path ever moved every commit in every repo passed the secret scan silently, no output, exit 0. DEMONSTRATED: same hook, same AWS key pair; binary present blocks the commit, path broken commits it clean and prints nothing. Binary is present today (8.30.1) and all 23 repos under dev/ carry the hook, so the gate is live -- the failure is one uninstall away and invisible. HARDENED TEMPLATE 27 Aug 2026: winget path, then PATH fallback, then block loudly naming the reason. A moved install keeps working; a real absence stops the commit instead of waving it through. Template only: the 23 existing repos still carry the old copy because init.templateDir applies at init/clone, and rolling it out mid-session would change commit behaviour under five live sessions.','verified','found by Magi Reader; independently demonstrated both directions','2026-08-26 18:23:45','2026-08-26 18:23:45','grep -c ''could not be found'' C:/Users/Admin/.git-templates/hooks/pre-commit   # expect 1');
INSERT INTO "facts" VALUES(92,'trap','magi-app-has-no-secret-scanning','All 23 repos under dev/ carry a gitleaks pre-commit hook. magi-reader-engine does NOT, and it is the repo that gets published. It lives at Downloads/Legacy.../magi-app, outside dev/, so a sweep whose denominator is dev/ reports 23 of 23 clean and misses it entirely. It uses husky with core.hooksPath=.husky/_ and its pre-commit is ''npx lint-staged''; nothing in .husky or package.json mentions gitleaks. Downloads/testgrader IS scanned, so the gap is specific rather than a Downloads problem. Verified 27 Aug 2026 by reading the hook and by committing a real-shaped AWS key pair into a scratch clone, which succeeded. THE GENERAL POINT: when auditing coverage, the denominator must be every repo on the machine, not every repo in the folder where repos are supposed to live.','verified',NULL,'2026-08-26 18:27:01','2026-08-26 18:27:01','grep -rl gitleaks ''<magi-app>/.husky'' ''<magi-app>/package.json''  -- no output means no secret scanning');
INSERT INTO "facts" VALUES(93,'trap','a-weak-canary-produces-a-FALSE-DEFECT','The mirror of the zero rule, and it bites in the opposite direction. Testing gitleaks, my first canary was ''ghp_'' plus 36 identical characters. It committed clean and I nearly reported the security tool broken. The canary was the problem: low entropy, correctly ignored. Two further passes were AWS''s own PUBLISHED example keys, which gitleaks deliberately allowlists. Four apparent failures, zero real ones. So: an instrument that fails your test may be right and your test may be wrong, and ''the security tool is broken'' is a finding people act on quickly. Make the canary realistic, and when a tool disagrees with your test, suspect the test first.','verified',NULL,'2026-08-26 18:27:01','2026-08-26 18:27:01',NULL);
INSERT INTO "facts" VALUES(94,'trap','repo-audit-denominator-is-the-machine','A coverage audit''s denominator must be every repo on the MACHINE, not every repo in the folder where repos are supposed to live. Two sessions independently reported ''23 of 23 repos have the gitleaks hook'' and both counted the same wrong set: there are 26. The three outside dev/ are magi-app (published as magi-reader-engine, uses husky with per-repo core.hooksPath=.husky/_ and NO gitleaks), Downloads/testgrader (scanned, fine), and source/repos/demo_selfhelp (empty, 0 commits, remote belongs to xM4sterMindx not Dan). SECOND HALF: checking ''git config --global core.hooksPath'' is not enough -- a PER-REPO core.hooksPath silently redirects hooks away from .git/hooks, which is exactly how magi-app escaped. Query it per repo, without --global.','verified','find for .git across the profile, 2026-08-27; magi-app gap found by Magi Reader','2026-08-26 18:29:11','2026-08-26 18:29:11','cd C:/Users/Admin && find . -name node_modules -prune -o -type d -name .git -print | wc -l   # expect 26, not 23');
INSERT INTO "facts" VALUES(95,'project','magi-app-scanned-clean','magi-app (Downloads/Legacy.../magi-app, published as dancockrell/magi-reader-engine) had NO secret scanning: husky pre-commit runs only ''npx lint-staged''. Audited 2026-08-27 and it is CLEAN: gitleaks over 56 commits / 30.43 MB found no leaks; 166 tracked files carry no credential-shaped names, and none was ever added and later deleted. Canaries proved both instruments fire. The gate is still absent -- the fix is adding gitleaks to .husky/pre-commit, left to the Magi Reader session since they are committing to it live.','verified','gitleaks via a NATIVE Windows path; the MSYS /c/ form fails FTL and scans nothing','2026-08-26 18:29:11','2026-08-26 18:29:11',NULL);
INSERT INTO "facts" VALUES(96,'trap','gitleaks-needs-native-windows-path','gitleaks.exe is a Windows binary and cannot resolve MSYS-style /c/Users/... paths. Given one it prints ''FTL CreateFile ... cannot find the path'' and scans nothing. Loud rather than silent, so it fails safe -- but a scan that reports 0 commits is not a clean scan. Always pass C:/ or C:\ form, and read the commits-scanned line before believing ''no leaks found''.','verified','magi-app scan, 0 bytes via /c/ vs 30.43 MB via C:\','2026-08-26 18:29:11','2026-08-26 18:29:11','gitleaks detect --source C:/Users/Admin/dev/memory-db --no-banner   # expect a non-zero commits-scanned count');
INSERT INTO "facts" VALUES(97,'trap','husky-runs-hooks-with-sh-e','husky v9''s wrapper (.husky/_/h) invokes hooks as `sh -e "$s"`, so ANY command returning non-zero kills the hook on that line. This silently removes error reporting from hooks that look correct: `scan=$(gitleaks protect --staged)` exits the script the instant gitleaks finds something, BEFORE the exit code is read and before any message prints, so the caller sees only ''husky - pre-commit script failed (code 1)''. It blocks correctly and explains nothing, which reads as output suppression rather than an early exit and cost about an hour to diagnose. Hit TWICE in one file: the same trap sat on the `command -v` fallback assignment. FIX: put the command in an `if` condition (exempt from -e) or append `|| true`. Note also that a hook''s messages should go to STDERR; stdout from a hook is not reliably shown.','verified',NULL,'2026-08-26 18:37:37','2026-08-26 18:37:37','grep -n ''sh -e'' <repo>/.husky/_/h   -- present means every non-zero line is fatal');
INSERT INTO "facts" VALUES(98,'trap','no-itch-game-resolves-for-this-key','27 Aug 2026: butler cannot reach ANY itch game for this account. The key authenticates and the user resolves -- a bogus account gives ''invalid target (bad user)'' while dancockrell/<anything> gives ''invalid game'', which is a different error -- but every slug tried fails, INCLUDING dancockrell/ghost-front, which is hard-coded in the working push script at dev/gf-tools/tools/push.sh and therefore existed. dancockrell.itch.io 302-redirects to itch.io/profile/dancockrell with no projects listed, which is what itch does when a user has no game pages. So either the itch projects were deleted, or ~/.config/itch/butler_creds (42 bytes, modified 21 Aug) belongs to a different account than the games did. Butler CANNOT create a game and has no command to list games -- every subcommand needs a target you already know -- so this cannot be resolved from the CLI. The project page has to be created or identified in the itch.io web UI first. Never open or print butler_creds.','verified',NULL,'2026-08-26 23:59:16','2026-08-26 23:59:16','butler status dancockrell/ghost-front   -- ''invalid game'' means no reachable project; a channel listing means it is fixed');
INSERT INTO "facts" VALUES(99,'tool','magi-reader-release-artifacts','npm run release in magi-app produces two zips in release/, named from package.json version. At 0.8.0: magi-reader-0.8.0-reader.zip (748 files, 29.3 MB) and magi-reader-0.8.0-legacy.zip (745 files, 29.5 MB). Both verified with butler auditzip (''Everything checks out''), both carry index.html at the archive root, and both sit under itch''s 1000-file limit, which is the constraint that shaped the pack format. release/ is gitignored; the git tag is what is durable. NOTE: npm run release chains verify:full first, which re-runs the whole e2e suite and fails intermittently on the @serial itch test under load; the build steps can be run directly when HEAD has already passed the chain at push time.','verified',NULL,'2026-08-26 23:59:16','2026-08-26 23:59:16','cd magi-app && ls -la release/*.zip && butler auditzip release/magi-reader-*-reader.zip');
INSERT INTO "facts" VALUES(100,'trap','iso-date-only-parses-as-utc','An ISO date-only string parses as MIDNIGHT UTC (spec), but Date.now() is an instant, so subtracting them on a machine east of UTC gives a NEGATIVE age for something added today. Math.floor turns -0.09 days into -1, and any "age >= threshold" test then silently never fires. Cost: a staleness check in dr-genie-settings that could not fire at all, while printing "-1 days" on screen under a summary that said "all passed". Fix: take BOTH sides at UTC midnight - Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()) minus Date.parse(dateOnly) - use Math.round, and make a negative age a hard failure rather than clamping it, since a future date is a typo that would hide the entry from ageing for as long as it stayed wrong. This machine is east of UTC, so the bug reproduces here and would be invisible in a US timezone.','verified',NULL,'2026-08-27 00:02:01','2026-08-27 00:02:01','cd /c/Users/Admin/dev/dr-genie-settings && DR_STALE_DAYS=0 node validate.mjs | tail -1');
INSERT INTO "facts" VALUES(101,'reference','itch-target-gift-of-the-magi','The itch.io target for Magi Reader is dancockrell/the-gift-of-the-magi, channel html. Pushed 0.8.0 on 27 Aug 2026: build #1919082, upload #18973417, 29.26 MiB. The slug was expensive to find because the project is a DRAFT -- drafts are 404 to anonymous fetch and absent from the public profile, and butler has no command to list games, so every subcommand needs a slug you already know. Probe with butler status dancockrell/<slug>: ''invalid game'' means wrong slug, ''invalid target (bad user)'' means wrong account, and ''No channel found'' means the project exists and is empty. Push with: butler push release/magi-reader-<v>-reader.zip dancockrell/the-gift-of-the-magi:html --userversion <v>','verified',NULL,'2026-08-27 00:09:23','2026-08-27 00:09:23','butler status dancockrell/the-gift-of-the-magi   -- a channel table means the target is live');
INSERT INTO "facts" VALUES(102,'trap','butler-cannot-create-an-itch-project','butler creates CHANNELS, never PROJECTS. A channel comes into existence as a side effect of a successful push; the push itself fails first if no project exists, with ''creating build on remote server: itch.io API error (400): /wharf/builds: invalid game''. There is no butler command to make a game and none to list games. The project page must be created at itch.io/game/new in the web UI, with Kind of project set to HTML for it to be playable in a browser rather than a download. Also note butler push --dry-run does NOT contact the API at all -- it only lists local files, so it cannot be used to test whether a target resolves. Use butler status for that.','verified',NULL,'2026-08-27 00:09:23','2026-08-27 00:09:23',NULL);
INSERT INTO "facts" VALUES(103,'reference','itch-target-the-raven','The Raven''s itch project is dancockrell/the-raven-edgar-allen-poe -- note ALLEN, not Allan, which is a misspelling of Poe''s name carried in the slug and the page title. Zero channels as of 27 Aug 2026; NOT pushed, see [[raven-has-no-forward-build-tool]]. The Gift of the Magi is at dancockrell/the-gift-of-the-magi and IS pushed at 0.8.0. Both projects are RESTRICTED, which is itch''s default for a new project and which Dan opens manually.','verified',NULL,'2026-08-27 00:10:59','2026-08-27 00:10:59','butler status dancockrell/the-raven-edgar-allen-poe');
INSERT INTO "facts" VALUES(104,'trap','raven-has-no-forward-build-tool','The Raven repo''s pipeline runs only BACKWARDS: build/the-raven.html -> extract-book.mjs -> book/book.json -> fix-glossary.mjs -> pack/book.json. Nothing goes pack -> build; both tools in tools/ only READ the html. So edits to pack/book.json cannot be shipped, because the only distributable artifact is build/the-raven.html, dated 25 Aug and never regenerated. PROVEN 27 Aug 2026: after fixing the book''s questions, build/the-raven.html still contains ''Morning will never come'' and ''holy, made a saint'' (the old text) while pack/book.json contains ''Dawn is still a great many hours away'' and ''holy and blessed''. Pushing that build to itch would silently ship back the 50% answer-position bias, the 82% longest-option tell, the circular gloss and the absolute distractors -- undoing the fixes invisibly, because the artifact looks current. The magi engine cannot ship it either: it loads books from src/books/ and the raven lives in its own pack repo, with the bring-your-own-pack contract still unbuilt.','verified',NULL,'2026-08-27 00:10:59','2026-08-27 00:10:59','grep -c ''Morning will never come'' <raven>/build/the-raven.html  -- 1 means the build is still stale');
INSERT INTO "facts" VALUES(105,'tool','raven-forward-build-tool','BUILT 27 Aug 2026, closing the gap in [[raven-has-no-forward-build-tool]] which is now RESOLVED. tools/build-reader.mjs in the raven repo writes pack/book.json back INTO build/the-raven.html: it replaces the TEACHING literal wholesale and swaps changed gloss definitions individually. Refuses if the pack lacks a unit the build has, if a gloss string is not unique in the file, if the size moves by more than the edit explains, or if the rewritten literal does not read back as the pack. tools/lib-literal.mjs finds a balanced `var NAME = {...}` span (lifted from the engine''s extract-book.mjs; a regex cannot do it because the stanzas are full of braces). Art and audio are data URIs elsewhere and are never touched. Run: node tools/build-reader.mjs [--write]','verified',NULL,'2026-08-27 00:18:28','2026-08-27 00:18:28','cd <raven> && node tools/build-reader.mjs   -- ''The build already matches the pack'' means they are in sync');
INSERT INTO "facts" VALUES(106,'trap','raven-pack-is-missing-its-act-reviews','pack/book.json in the raven repo has NO recaps: 28 mc questions across 14 units and zero act reviews, where the shipped build has five (s3, s6, s8, s10, s12). They live in a separate `var RECAPS = {...}` literal in the HTML, and the engine''s extract-book.mjs folds them into teaching[id].recap -- a fold that was ADDED after this pack was generated, so the pack predates it. Consequence: a pack-driven reader loses all five act reviews, exactly the way four magi act reviews once shipped unasked. The shipped single-file build is unaffected, because RECAPS is deliberately untouched by tools/build-reader.mjs. Fix is to regenerate the pack from the current build with the current extractor, which was not done on 27 Aug to avoid mixing it into the release.','verified',NULL,'2026-08-27 00:18:28','2026-08-27 00:18:28','node -e "const b=require(''<raven>/pack/book.json'');console.log(Object.values(b.teaching).filter(t=>t.recap).length)"   -- 0 means still missing, 5 means fixed');
CREATE TABLE projects (
    name        TEXT PRIMARY KEY,
    path        TEXT,
    repo        TEXT,
    stack       TEXT,
    status      TEXT DEFAULT 'active' CHECK (status IN
                  ('active','paused','archived','published')),
    notes       TEXT,
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "projects" VALUES('dr-companion','C:/Users/Admin/dev/dr-companion','dancockrell/dr-companion','Tauri (Rust + web)','active','Automates Lich. Needs Ruby4Lich5.','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('ghost-front','C:/Users/Admin/dev/ghost-front','dancockrell/ghost-front','single-file HTML','published','WW2 horror platformer','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('raven-classroom','C:/Users/Admin/dev/raven-classroom','dancockrell/raven-classroom','HTML + Apps Script','published','Reader engine behind Raven/Magi/Long Night','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('quickgrade','C:/Users/Admin/Downloads/testgrader','dancockrell/quickgrade','PWA','published','Offline paper grader; student data never leaves device','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('world-aflame','C:/Users/Admin/dev/world-aflame','dancockrell/world-aflame','HTML + WebRTC','archived','Superseded by world-aflame-godot per Dan (2026-08-26): ''everything else is deprecated and archived.'' Original 3-faction web/JS card game; repo/Pages left live as-is, no further development planned here.','2026-08-26 15:56:57');
INSERT INTO "projects" VALUES('longnight','C:/Users/Admin/dev/longnight','dancockrell/longnight','canvas RPG','active','Synthesised orchestra, no audio downloads','2026-08-26 15:29:46');
INSERT INTO "projects" VALUES('world-aflame-godot','C:/Users/Admin/dev/world-aflame-godot',NULL,NULL,'published','Active development. Godot 4.7.2 (Standard/non-Mono build required for Web export -- Mono build has zero Web templates). Two rulesets: Classic (turn-based, faithful GDScript port of the web version''s engine + all 150 cards, live-hosted, P2P via NetManager) and Skirmish (new, Snap-inspired simultaneous-reveal mode, 1500 generated keyword-driven cards, engine-verified but UI still landing). Hosted at https://dancockrell.github.io/world-aflame-godot/ via gh-pages branch.','2026-08-26 15:58:37');
INSERT INTO "projects" VALUES('magi-reader-engine','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\magi-app','https://github.com/dancockrell/magi-reader-engine','React 19, Vite 8, Playwright, Google Apps Script','active','The illustrated reading engine for language classrooms, named after The Gift of the Magi. One engine, many books: a book is a pack under src/books and src/engine.test.js fails if engine code names a title, an author or a book id. 676 unit tests, 642 e2e across four browser engines. Still in Downloads rather than dev, against the usual rule.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('the-gift-of-the-magi-o-henry-magi-reader','C:\Users\Admin\Downloads\Legacy builds and Assets...if you can''t find something, try here\magi-app\src\books\magi','https://github.com/dancockrell/the-gift-of-the-magi-o-henry-magi-reader','book pack: JSON plus media','active','Still inside the engine repository, not yet split out. Blocked on step 2 of PLAN.md, the bring-your-own-pack contract. The engine now has its own fixture book so the tests no longer need this one.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('the-raven-edgar-allan-poe-magi-reader','C:\Users\Admin\dev\the-raven-edgar-allan-poe-raven-reader','https://github.com/dancockrell/the-raven-edgar-allan-poe-magi-reader','book pack: JSON, 368 mp3, WebVTT','active','Poe''s poem as a Magi Reader book. Narration and word-level cues recovered from raven-itch-folder zips and committed. Note the folder on disk still says raven-reader while the repo says magi-reader.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('magi-reader-classroom-toolkit',NULL,'https://github.com/dancockrell/magi-reader-classroom-toolkit',NULL,'archived','Was raven-classroom, renamed 2026-08-26. Provenance, not a product: the toolkit the engine grew out of, still holding the QR check-in page and the voice generators. Its old description called it the engine behind Raven, Magi and The Long Night, which was wrong on both counts: it is not the engine, and it has nothing to do with The Long Night.','2026-08-26 16:03:24');
INSERT INTO "projects" VALUES('project-42-blockchain','C:/Users/Admin/dev/project-42-blockchain','dancockrell/project-42-blockchain','GDScript library','active','Dual-signature hash-chain ledger, MIT, no server or currency. Renamed from witness-chain. Consumed by world-aflame-godot for Elo. Open issue #1 requests key persistence, DAG timestamp-ordered iteration, an append() payload-validator hook, and a distinct-cosigner-count helper.','2026-08-26 16:17:49');
INSERT INTO "projects" VALUES('claude-config','C:\Users\Admin\dev\claude-config',NULL,'python, git','active','Local git history for the hand-written parts of C:\Users\Admin\.claude. Created 27 Aug 2026 after four sessions edited CLAUDE.md concurrently, one corrupted it through a heredoc, and the only fallbacks were two ad-hoc .bak files at 289 and 472 lines against a live 997. 41 files, about 150 KB, by allowlist. NO REMOTE, deliberately: it holds personal notes and whether it ever gets one is Dan''s call, private if so. Run: python snapshot.py --commit. Guards proved by test_snapshot.py, three of whose four cases pass only by refusing.','2026-08-26 18:07:00');
CREATE INDEX idx_facts_category ON facts(category);
CREATE INDEX idx_events_ts   ON events(ts);
CREATE INDEX idx_events_kind ON events(kind);
CREATE TRIGGER facts_touch
AFTER UPDATE ON facts FOR EACH ROW
BEGIN
    UPDATE facts SET updated_at = datetime('now') WHERE id = OLD.id;
END;
CREATE TRIGGER projects_touch
AFTER UPDATE ON projects FOR EACH ROW
BEGIN
    UPDATE projects SET updated_at = datetime('now') WHERE name = OLD.name;
END;
CREATE TRIGGER deps_touch
        AFTER UPDATE ON dependencies FOR EACH ROW
        BEGIN UPDATE dependencies SET updated_at = datetime('now') WHERE id = OLD.id; END;
CREATE TRIGGER deps_stamp
        AFTER INSERT ON dependencies FOR EACH ROW WHEN NEW.updated_at IS NULL
        BEGIN UPDATE dependencies SET updated_at = datetime('now') WHERE id = NEW.id; END;
COMMIT;